### ISSUE TITLE
Special solution explorer for Unity projects

### ISSUE THREAD

**Issue by WeslomPo** [JetBrains/resharper-unity#106]
Solution explorer is ugly and rigid, looks like relic of the past. Assemblies is not point of interest in Unity. Whole Assets folder more interest than splited by not trivial rules four or five roots.
Maybe it's just a matter of habit, but I used the editor where the whole project was just Assets folder with text files, and with this it was easier to work several times than here. 

Assemblies this is where  assembler is lives? xD I want more high level view window.

**Comment by cmcpasserby** [comment]
shift+shift, or ctrl+n Search works really good in all JetBrains products so i find i just dont even use the solution explorer at all.

**Comment by CAD97** [comment]
The solution layout is the same as that in Visual Studio, and is the way that it is because that is the way the project is laid out for Unity. Each project in the solution has meaning to the Unity build process.

In any case, the IntelliJ platform seems to prefer pushing the "smart" navigation features it provides:

- Search Everywhere <kbd><kbd>Shift</kbd><kbd>Shift</kbd></kbd>
- Go to Class <kbd><kbd>Ctrl</kbd>+<kbd>N</kbd></kbd>
- Go to File <kbd><kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>N</kbd></kbd>
- Recent Files <kbd><kbd>Ctrl</kbd>+<kbd>E</kbd></kbd>
- Navigation Bar <kbd><kbd>Alt</kbd>+<kbd>Home</kbd></kbd>

If you learn these shortcuts and use them, you shouldn't need the Solution Explorer. In fact, the Navigation Bar handles similarly to just having a folder open. In any case, the Unity workflow has always been to select files in the Unity Editor to then edit. There is no reason to change that now, as it works well -- in fact, moving files outside of the Unity Editor usually leads to losing the `.meta` file and breaking references.

**Comment by WeslomPo** [comment]
I mean that view:
![image](https://cloud.githubusercontent.com/assets/310008/23135522/7871d24c-f7b2-11e6-9946-f44be3efaac9.png)
You may surprised, but if you move files there, you don't loose meta links, it works as needed.
Solutions viewer not necessary in unity, all files in assets folder just a assets, and sometimes you want to edit them as regular text files. Solutions is not clear to understand where your file been live, if you want manipulate them somehow. Also, after creating folder you may loose it after switch-to-unity/switch-back, and can't add it again because that folder exists somewhere in another solution or on disk, but nowhere in solution. You need to add files from unity - that's broke you mood, if forces you to stop coding and start moving files around, clearing stupid unity template after and etc.
After 3 years of regular, everyday experience in coding Unity3D, I can not remember a single case, I need a solution viewer. I just do not ever need it. This ridiculously clumsy and useless window. Simple explorer works better than that window.

**Comment by cmcpasserby** [comment]
I dont think so, when looking for files in my Assets folder, `shift+shift` or `ctrl+n` are good enough or simply just finding it in unity. But what the sln explorer is good for is when you are building your own assemblies for Unity. It provides a easy way to see all the assemblies used for my project and a way to manually build a dll for each one.

**Comment by WeslomPo** [comment]
@cmcpasserby this is the only case where it is necessary. When you need other things, that have a regular basis, that you doing many times per day - solution view doing it worse. It low level viewer, that not needed in regular case. You made assembly once and it live long, but you don't need to maintain it, unity maintain it for you.
For some reason, you need to work with file structure made for computers all the time, instead a regular project folder that you maintain by your hands.

**Comment by jcx** [comment]
the dude is right, we need the merged window

if you are the all-skill dev you absolutely NEED the UnityVS's Unity Project Explorer and btw in the visual studio the plugin is broken in last verstion and it's painfull to need to go to Unity just to create folder or file

I understand the coders only, sure you can use the shortcut but think about us who must do all the things and not just coding .... unity project isn't the same thing like .net project 

BTW this is reason I am staying in visual studio, because i need smooth workflow more then refactor :D

**Comment by van800** [comment]
cross-reference https://rider-support.jetbrains.com/hc/en-us/community/posts/115000564664-Rider-Solution-Explorer-for-Unity

**Comment by van800** [comment]
Rider is going to have a file system explorer relatively soon, but it is not exactly Unity Project Explorer.

Please correct me, if I am wrong.
Unity Project Explorer in VS shows only scripts. Does it feel right?
I would expect it to include everything, which is currently added to Rider Solution Explorer. Stuff like shaders and files by "Additional extensions to include" set in Unity.

**Comment by jcx** [comment]
that would be actually much better to see everything, maybe with some filter options because I'd like to see even .meta files from time to time :D

btw if you include script templates with some reasonable location you'd make ultimate dev's helper :D because unity have them inside installation folder and that means you need to copy them every time you install new version

anyway ... the moment there's the browser I am leaving VS

**Comment by van800** [comment]
@jcx got your point, thanks.

Could you please comment more about script templates in the separate issue, which I opened?
https://github.com/JetBrains/resharper-unity/issues/232
Do you mean that you have a collection of templates, which you copy to Unity installation folder? Is there ability to use those templates in VS?

**Comment by SugoiDev** [comment]
With custom assemblies in Unity 2017.3+, a cleaner project view will probably be even more relevant.

I'm following [this thread](https://forum.unity.com/threads/example-project-assembly-definition-files.482313/page-4) on the Unity forum and it's possible that asset developers will begin splitting their assets into multiple assemblies soon. A project view that sees files and folders will help a lot with keeping this manageable.

**Comment by van800** [comment]
related to https://youtrack.jetbrains.com/issue/RIDER-12576

**Comment by van800** [comment]
Available in the current nightly build via [Jetbrains Toolbox App](https://www.jetbrains.com/toolbox/download/).
