### ISSUE TITLE
Hide Unity symbol in Rider

### ISSUE THREAD

**Issue by thebspin** [JetBrains/resharper-unity#109]
I just picked up Rider again with this plugin and its showing Unity icons at the same place you put the breakpoints. But for the love of god i can't find a option to turn these off. Is this even possible?

**Comment by citizenmatt** [comment]
Right now, no, but there is another issue to hide the icons (#94). (Also, there won't be a way to configure this in Rider yet, as a plugin can't yet do anything that needs a UI. Plugins are still very experimental)

But the icons shouldn't get in the way of breakpoints - the breakpoint lives in a column next to the gutter icon, rather than in the same column.

**Comment by thebspin** [comment]
Yes its not blocking anything its just something that has been annoying me. I'll guess i have to live with it for the time being or hide all the gutter icons.

**Comment by citizenmatt** [comment]
Yeah. I like the idea of marking Unity methods and serialised fields, but it can get a little noisy. I will add an option, and you'll be able to configure it in ReSharper at the least (or hand edit a .sln.dotSettings file). I'm going to close this in favour of #94.
