### ISSUE TITLE
Add custom attribute to mark method as not-frequently-called

### ISSUE THREAD

**Issue by dubois** [JetBrains/resharper-unity#1183]
Similarly to #1030, can we have the ability to mark methods as not being frequently called?

I work on a project that needs to run at VR frame rates on mobile hardware, so we're comfortable grappling with performance issues. However, the structure of our code creates too many false positives for the "performance critical context" feature to be useful for us. 

A lot of our code lives in manager classes which are updated once per frame; eventually the call stack leads all the way up to a singleton's `MonoBehaviour.Update()`. All this code is getting tagged as performance-critical, but we don't consider it to be "hot".

Specifically, something like this would work for us:
```
        public static bool HasFrequentlyCalledMethodAttribute(IFunctionDeclaration functionDeclaration)
        {
            return HasSpecificAttribute(functionDeclaration, "FrequentlyCalledMethodAttribute")
+               && !HasSpecificAttribute(functionDeclaration, "NotFrequentlyCalledMethodAttribute");
        }
```
and in our code
```
public class Application : MonoBehaviour {
  [AttributeUsage(AttributeTargets.Method)]
  private class NotFrequentlyCalledMethodAttribute : Attribute {
  }

  [NotFrequentlyCalled] // only once per frame
  void Update() {
    // propagate to managers ...
  }
}

```

**Comment by citizenmatt** [comment]
See also [RIDER-27955](https://youtrack.jetbrains.com/issue/RIDER-27955)

**Comment by FredTuna** [comment]
The attribute would be a nice addition. I would ask for something even more specific: to be able to tag a specific method call as not expensive. Within an Update function , some lines might be known to not be called every time the Update function is called (whereas the rest of the code in the Update function will be called every frame). So marking a specific method call or section of code as not expensive would help a lot in this situation.

**Comment by citizenmatt** [comment]
You can already ignore an existing method invocation with a comment. Alt+Enter on the highlight, open the "Inspection" sub menu and select "Disable once with comment".

<img width="695" alt="Screenshot 2019-05-16 at 16 16 20" src="https://user-images.githubusercontent.com/222659/57865764-189b4580-77f6-11e9-8893-ad41d66c9e99.png">

**Comment by FredTuna** [comment]
Yes I saw that option. Unfortunately it doesn't propagate to the method declarations. Here is an example:

Before disabling with comment:
![image](https://user-images.githubusercontent.com/23663597/57867023-62703580-77ce-11e9-90ec-5f310610c8d1.png)

After disabling with comment:
![image](https://user-images.githubusercontent.com/23663597/57867128-8d5a8980-77ce-11e9-857c-903c7a5a1b26.png)

In less trivial cases, seeing the fire icon next to a method makes me go up the method calls until I see where this is called to cause it to be in Performance Critical context. Only to find out it is in a rarely called section of an Update loop or Coroutine. Disabling it using the disable once comment will not remove all of the Performance indicators (fire icons and solid red underline) caused by this one method call.

It would also be nice if I didn't need to add comments in my code for Rider/Resharper specific features but I understand it might not be trivial to do without.

**Comment by DoubleLoopAndy** [comment]
I'd like to throw my support in for disabling the analysis at the method definition, too. You might have a call to Debug.Log that's extremely rare, yet the expensive method notification shows up without being able to understand that rarity.

**Comment by Domonion** [comment]
Hello guys, From the next EAP, you will be able to add `// ReSharper disable Unity.PerformanceAnalysis` comment to remove undesired methods from Performance analysis. Here is an example:
![java_0YBFhgduEB](https://user-images.githubusercontent.com/12771085/96588631-9406fd80-12ec-11eb-8817-fd763c722a98.png)
This will work transitively. There are some context actions, quick fixes, and code vision provided for convenience, for more information look #1248. 
Also from now on, it is possible to mark custom methods as expensive or performance-critical, for more information look #1030
