### ISSUE TITLE
Add support for SerializeReference

### ISSUE THREAD

**Issue by citizenmatt** [JetBrains/resharper-unity#1340]
New in Unity 2019.3.

* Applied to a field
* Applied only to reference types - the field is serialised as a reference, not a value, allowing for e.g. expressing object graphs

Initial thoughts:
* Means implicit use + assignment (like `[SerializeField]`)
* Need to treat these fields as serialised fields (naming standards, in use, context actions, code vision)
* Update "make serialised field" context actions - make serialised field/make serialised references
* Update `sprop` and `sfield` Live Templates? Allow choosing attribute?
* Only support in Unity 2019.3+

See more details in [the Unity forum](https://forum.unity.com/threads/serializereference-attribute.678868/)

**Comment by citizenmatt** [comment]
If this supports polymorphic serialisation, it might be useful to highlight when a subtype isn't `[Serializable]`

**Comment by citizenmatt** [comment]
Other possible issues:

* Check if things break if the class is renamed - the class name might be part of the serialised data
* It looks like the serialised object can't derive from `UnityEngine.Object`. If so, add a warning + "Why is Rider suggesting this?" for this scenario.

**Comment by aybe** [comment]
There's a bug in Rider 2020.2.4:

`TrackPerk` is abstract, it is and all its derived marked as `[Serializable]`.

The bug is as follows, 

I wanted to add `[HideInInspector]` but it's marked as useless, tried to add `[SerializeField]` but it's also marked as useless.

![rider64_2020-11-02_19-51-42](https://user-images.githubusercontent.com/1537591/97906976-d98fe580-1d44-11eb-9166-33495b031ebb.png)
