### ISSUE TITLE
Support for NoReorder attribute ?

### ISSUE THREAD

**Issue by aybe** [JetBrains/resharper-unity#1496]
As you know, the order in which fields are laid out in a class is the order they will be shown in an Inspector.

Since the attribute is not available in Unity, the only way to prevent code formatting reordering these fields is to wrap them all in a region.

Will NoReorder be supported at some point in the future ?

**Comment by citizenmatt** [comment]
This is unfortunately a question for Unity - they're using an older subset of the annotation attributes. We're currently talking to them to see if they'll update. In the meantime, you can add the attributes to your own project and Rider/ReSharper will use them.

You can do this by using the _Copy C# implementation to clipboard_ button in _Preferences | Editor | Inspection Settings | Code Annotations_ and pasting into a new file in your project. You will have to make some edits - delete the attributes that Unity is already shipping.

We do have an outstanding issue (#88) to automatically not reorder serialised fields. We should revisit this.

**Comment by aybe** [comment]
Thank you.

**Comment by aybe** [comment]
Bump,

Even when adding custom annotations to a Unity project, `NoReorder` is never honored.

**Comment by citizenmatt** [comment]
Good news - Unity have just updated their annotations in Unity 2020.1, 2019.3 and 2018.4, so all attributes that make sense for Unity will be added. Adding your own implementation of `NoReorder` does work. You'll need to make sure that you add the class inside the `JetBrains.Annotations` namespace, called `NoReorderAttribute` and deriving from `Attribute`. Apply this to a MonoBehaviour class and none of the type members, including serialised fields will be reordered.

And there's more good news - #88 will be fixed in Rider 2020.2, as a new API has been added that allows plugins to add extra rules to code cleanup without trashing existing rules. Unfortunately, this was added a little too late for the Unity plugin to make use of it in this release, but it will make it into Rider 2020.2, and then code cleanup will automatically do the right thing for serialised fields.

**Comment by SugoiDev** [comment]
Does this respect a custom "Default annotations namespace"? Mine is `JetBrains.LAAnnotations`

![image](https://user-images.githubusercontent.com/7355630/78184117-5c636180-743f-11ea-846c-3b73edb97fc1.png)

**Comment by aybe** [comment]
@citizenmatt good news !

**Comment by citizenmatt** [comment]
@SugoiDev I haven’t tested it, but it should work just fine.

**Comment by aybe** [comment]
Sorry to bump on this,

I have followed all of your instructions:
 - Visual Studio 2019
 - Unity 2019.3.10f1
 - added custom annotations copied from clipboard

But the `NoReorder` attribute is never honored at all :(

All other attributes are recognized correctly such as `CanBeNull` etc.

Do you have any idea on what could be wrong on my side?

Thank you!

**Comment by citizenmatt** [comment]
Can you give me an example of the code you've got `NoReorder` applied to?

Also, I'm planning on natively supporting Unity classes in code cleanup for Rider 2020.2 - the code cleanup profile will include a snippet for Unity classes that recognise serialise fields, and group them without reordering. I have an initial implementation done, it just needs some clean up ha ha.

**Comment by aybe** [comment]
Well, I've just read the docs and ... I should have better actually !

```
NoReorderAttribute﻿
Prevents the Member Reordering feature from tossing members of the marked class.

The attribute must be mentioned in your member reordering patterns.

For more information, see Rearrange Members with File and Type Layout Patterns
```

I thought this attribute was taken care of automatically ...

As for an example, here is one:

```
[NoReorder]
public class Test
{
    public int B;
    public int A;
}
```

**Comment by citizenmatt** [comment]
The attribute is included in the default file layout pattern set, first pattern. Check _Preferences | Editor | Code Style | C# | File Layout_:

```
  <TypePattern DisplayName="Non-reorderable types">
    <TypePattern.Match>
      <Or>
        <And>
          <Kind Is="Interface" />
          <Or>
            <HasAttribute Name="System.Runtime.InteropServices.InterfaceTypeAttribute" />
            <HasAttribute Name="System.Runtime.InteropServices.ComImport" />
          </Or>
        </And>
        <Kind Is="Struct" />
        <HasAttribute Name="JetBrains.Annotations.NoReorderAttribute" />
        <HasAttribute Name="JetBrains.Annotations.NoReorder" />
      </Or>
    </TypePattern.Match>
  </TypePattern>
```

If I run code cleanup on this code snippet, it works as expected. `NoReorderTest` is reordered to be `A` then `B` and `NoReorderTest2` (with the attribute) is not reordered.

```
using System;
using JetBrains.Annotations;

namespace JetBrains.Annotations
{
    [AttributeUsage(
        AttributeTargets.Class | AttributeTargets.Interface | AttributeTargets.Struct | AttributeTargets.Enum)]
    public sealed class NoReorderAttribute : Attribute { }
}

namespace GemExample.Scripts
{
    public class NoReorderTest
    {
        public int B;
        public int A;
    }

    [NoReorder]
    public class NoReorderTest2
    {
        public int B;
        public int A;
    }
}
```

**Comment by aybe** [comment]
@citizenmatt you're right, it works out of the box on a freshly created project, thank you :)

**Comment by somethingSTRANGE** [comment]
I'm running Rider 2019.3.4 with an old project. I updated the layout with the TypePattern block @citizenmatt posted, and when adding the [NoReorder] attribute to the class, the class isn't reordered at all. Is the attribute supposed to just prevent fields (or serialized fields) from being reordered, or does it prevent the entire class layout from being cleaned up?  Normally constructors are placed above properties. When the attribute is added to the class, the constructor/property order is not enforced.

It would be great if just the fields could be marked with the "NoReorder" so that everything else is allowed to be cleaned up and sorted as before.

**Comment by citizenmatt** [comment]
Yes, the `NoReorder` attribute is a bit of a blunt tool. It prevents any reordering of any members inside the type it's applied to. It's mainly intended for things like (non-Unity) serialisation. For Rider 2019.3 (and indeed 2020.1) there's no other alternative. Rider 2020.2 (due any day now) has proper support, and will automatically recognise Unity classes. It reorders most type members as normal, without reordering serialised fields. It also recognises event functions, and will by default group and sort event functions separately to everything else. It's also a new pattern which you can edit and tweak to how you like it.
