### ISSUE TITLE
Fatal error initializing 'com.jetbrains.resharper.debugger.breakpoint.RiderBreakPointHost'

### ISSUE THREAD

**Issue by timgranstrom** [JetBrains/resharper-unity#153]
When trying to open c# scripts in Unity with Rider as an editor, I get the following error:
Fatal error initializing 'com.jetbrains.resharper.debugger.breakpoint.RiderBreakPointHost'

I have installed Rider, the resharper plugin, the plugin for the unity editor and restarted everything.

**Comment by duckinferno** [comment]
I'm getting this too.  

macOS sierra
Unity 5.6.1f1
Rider idon'tevenknowher 171.4456.199 

I installed the unity resharper plugin as part of rider's first-time setup.  
Have tried disabling the unity plugin to no avail.

![screen shot 2017-05-24 at 2 28 03 pm](https://cloud.githubusercontent.com/assets/3953262/26384432/44e4e56c-408d-11e7-93a1-c75d0c4b321f.png)

**Comment by ArsenyChernyaev** [comment]
Hello!
You could check issue progress here:
https://youtrack.jetbrains.com/issue/RIDER-5961

**Comment by van800** [comment]
Try to check the commandline with which Rider was started
ps aux |cat | grep "Rider EAP.app"
must be something like
/Applications/Rider EAP.app/Contents/MacOS/rider /Users/admin/RiderProjects/Unity3dRider/Unity3dRider.sln -l -1 /Users/admin/RiderProjects/Unity3dRider/Assets/Plugins/Editor/JetBrains/NewBehaviourScript.cs
If it doesn't contains path to sln, you may get weird errors.
To fix it - use https://github.com/JetBrains/Unity3dRider

**Comment by IvanPashchenko** [comment]
This can happen in two cases:
* Unity3dRider plugin is not installed.
 To fix this, install https://github.com/JetBrains/unity3drider plugin
* A project was opened in Unity and .sln file does not compile. This causes the Unity3dRider plugin to not compile too.
 To fix this, you should open .sln file directly in Rider and fix the errors. After that, the plugin will be compiled and .cs files should properly open. This only happens when you start Unity with non-compiling .sln, once in a session.

Also, this is planned to be fixed in the next rider EAP by presenting you with a choice of .sln file to open, even if the Unity3dRider is not installed.

**Comment by van800** [comment]
Please expect fix in Rider EAP build.

**Comment by IvanPashchenko** [comment]
@timgranstrom @duckinferno did the EAP23 fix this issue for you?

**Comment by duckinferno** [comment]
@IvanPashchenko I followed your suggestion of opening the .sln directly and it fixed it, ie. I didn't wait until EAP23 to see if that works.
