### ISSUE TITLE
Allow other file types to be treated as C#

### ISSUE THREAD

**Issue by weichx** [JetBrains/resharper-unity#1533]
Hi there, 

I have a bit of an odd request which is that I need to add C# files to my Unity project...that aren't C# files. Basically I'm using Roslyn directly to hot compile these scripts on the fly and load a dll at runtime (development only of course). This allows our team reload only certain modules of our game without recompiling the core game (which takes forever). 

I've marked our hot reloaded files with a .xxx extension and associated that extension with the C# file type. This works perfectly well but Rider basically ignores our .xxx files and won't provide any services other than basic syntax highlighting. It would be really awesome to have full C# support for this.

How can I get this to work?

**Comment by citizenmatt** [comment]
Unfortunately, this is an unsupported scenario. 

Right now, file type registration is handled in two places, only one of which has a UI, and sadly, these two don't talk to each other. The IntelliJ-based frontend provides a file type registration options page to associate a file extension with a specific file type, such as C#. But this doesn't do anything to tell the ReSharper based backend that the file type should be treated as C#. So it's not possible to get full C# functionality from a custom file extension.

This requires changes in core Rider, rather than the Unity plugin. There are a couple of tickets already open for it, you can vote and track progress there - check out [RIDER-11219](https://youtrack.jetbrains.com/issue/RIDER-11219) and [RIDER-15877](https://youtrack.jetbrains.com/issue/RIDER-15877)
