### ISSUE TITLE
Ability to filter log stacktrace

### ISSUE THREAD

**Issue by vertxxyz** [JetBrains/resharper-unity#1538]
I'm currently using Unitask in a project: 
![image](https://user-images.githubusercontent.com/21963717/75218808-41258680-57ef-11ea-99be-7c5f67fe1d6e.png)

Navigating the Unity stacktraces from async code like this is particularly bad. 

It would be nice to be able to exclude methods/namespaces/classes/etc from the trace to remove the visual clutter that goes into navigating between what's meaningful.

**Comment by citizenmatt** [comment]
You can already do this in the _Preferences | Editor | General | Console_ page.

You can add a line `at UniRx.Async` and all lines that contain that will be automatically folded in the Stack Trace Explorer, and also the Unity Logs console.

If this covers too many lines, and you still want to see some stack frames that contain `at UniRx.Async`, you can add multiple patterns, or add an exception so that it's not included ("exception" is an overloaded term when we're talking stack traces, think of it as "exclusion")

**Comment by vertxxyz** [comment]
Oh awesome! It might be appropriate to add a filter icon or turn the settings spanner into a dropdown so it's apparent that that settings page is relevant, because I wouldn't have known it was a shared setting without your help/trial and error

**Comment by van800** [comment]
@vertxxyz I have filed an issue to support that. Please vote https://youtrack.jetbrains.com/issue/RIDER-40201
