### ISSUE TITLE
Can't deactivate "Rename references in Unity asset files"

### ISSUE THREAD

**Issue by Baste-RainGames** [JetBrains/resharper-unity#1569]
I tried the Rider EAP, and I ran into this message when trying to rename a method parameter:

![image](https://user-images.githubusercontent.com/12800067/76610728-a4b2f200-6519-11ea-8769-f48d2862b754.png)

First of all, I don't want Rider to ever touch Unity asset files as a side-effect of renaming a variable. We don't use UnityEvents much, so the slowdown simply isn't worth it. I've turned of everything I can find relating to that. So why am I getting this message?

Secondly, I'm renaming a method parameter on a static method! That would never show up in Unity asset files, so this is overly aggressive.

![issue](https://user-images.githubusercontent.com/12800067/76612842-5dc6fb80-651d-11ea-8ee1-e6289f275f63.gif)

Hitting "next" seems to be harmless, but I'd really prefer it if I could rename things without having to press enter twice.

**Comment by citizenmatt** [comment]
Looks like a bug in the EAP. We're currently displaying the dialog when renaming any element inside a Unity class. Thanks for the report, we'll get it fixed.

As for ignoring assets, you should be able to disable everything in the _Preferences | Languages & Frameworks | Unity Engine_ settings page. Uncheck the _Parse text based assets_ option. Although this might not get rid of this dialog until we've fixed the bug.

**Comment by krasnotsvetov** [comment]
When you disable asset parsing, Rider will lose all features with asset integration (inspector values, usages). In 20.1 we significantly boost start-up performance for projects with large assets, memory footprint and high CPU usage while parsing large assets.

I hope, that asset integration is useful and want to introduce new settings which will allow disabling asset refactorings without disabling asset integration features (EAP 6)

Bug should be fixed in EAP 5
