### ISSUE TITLE
Host unity-rider project files in a new repo if they must be in my project.

### ISSUE THREAD

**Issue by EntranceJew** [JetBrains/resharper-unity#161]
I don't want my project files going old from anything in here with an experimental IDE, I would like to just version `Assets/Plugins/Editor/JetBrains/*` like a sub-module or a sub-tree, the current file structure does not make that possible even with sparse checkout.

**Comment by Rennan24** [comment]
Yea I agree but on a different basis, I like having plugins like this one go inside of the "Standard Assets" folder, but currently even, if I have the plugin inside of the "Standard Assets" folder it creates another one in the Plugins folder. It's pretty annoying and it would be awesome if there was an option to just disable it from automatically putting the files in. Especially since in the Unity Beta's it says
> Editor: Scripts willl be opened correctly in JetBrains Rider when selecting it as external script editor.

So it doesn't seem like this plugin will be very useful soon, unless if it also does some other cool things... Also funny thing seeing a person from the Love2D community here. 😄

**Comment by IvanPashchenko** [comment]
@Rennan24 
> So it doesn't seem like this plugin will be very useful soon, unless if it also does some other cool things..
It does add some context menu options which won't be added with a Unity Beta, so it's still useful :)

In the next release, we'll have an option to disable automatic Unity3dRider installation, see #159.

**Comment by Rennan24** [comment]
Awesome, Thanks for all the hard work guys! Keep it up!

**Comment by IvanPashchenko** [comment]
@Rennan24 
> Yea I agree but on a different basis, I like having plugins like this one go inside of the "Standard Assets" folder, but currently even, if I have the plugin inside of the "Standard Assets" folder it creates another one in the Plugins folder.

Also, we have another enhancement coming: After Rider has installed the plugin, you can move it wherever is convenient for you. Rider will now check the solution for plugin and update it in-place, and won't create a copy with the hardcoded path. This should be available with the next Rider release.

**Comment by van800** [comment]
Please feel free to reopen, if this is still valid
