### ISSUE TITLE
Rider suggest SerializeField on class definitions

### ISSUE THREAD

**Issue by JurjenBiewenga** [JetBrains/resharper-unity#1659]
Currently the auto-completion suggests that `SerializeField` can be used on anything, however this attribute should only be used on instance fields. Removing this from the auto-completions when it would be applied to a non instance field should prevent unnecessary auto-completion items.

**Comment by citizenmatt** [comment]
Rider will suggest all attribute types in completion, even if they're not valid at that point. Rider will then highlight any incorrectly applied attributes, so you can fix it.

The Unity plugin has specific support for `SerializeField` and a few other attributes to make sure they're applied at the correct place. If not, instead of the usual error (because normally it's a compile error), they are shown as redundant.

I don't think this plugin should filter attributes from the list. Personally, I'm ok that Rider doesn't, but I've created an issue: [RIDER-44415](https://youtrack.jetbrains.com/issue/RIDER-44415)
