### ISSUE TITLE
API compatability

### ISSUE THREAD

**Issue by Feacur** [JetBrains/resharper-unity#167]
#### See method GetLanguageLevel()
Convergence of expression "#if UNITY_4 || UNITY_4_6 || UNITY_4_7 || UNITY_5_0 || ..." into "false" doesn't mean expression "UNITY_5_6" converges into "true".

Because of that code potentially wouldn't compile or wrong value will be returned from the method.

I believe something like this will fit better:
`// Unity 5.5 supports C# 6, but only when targeting .NET 4.6. The enum doesn't exist pre Unity 5.5`
`#if UNITY_4 || UNITY_4_6 || UNITY_4_7 || UNITY_5_0 || UNITY_5_1 || UNITY_5_2 || UNITY_5_3|| UNITY_5_4 || UNITY_5_5`
`if ((int)PlayerSettings.apiCompatibilityLevel >= 3) { return "6"; }`
`#elif UNITY_5_6`
`if ((int) PlayerSettings.GetApiCompatibilityLevel(EditorUserBuildSettings.selectedBuildTargetGroup) >= 3) { return "6"; }`
`#endif`

**Comment by van800** [comment]
@Feacur Do I understand right, that
The present code is expecting that UNITY_5_6_OR_NEWER would support the API:
PlayerSettings.GetApiCompatibilityLevel(EditorUserBuildSettings.selectedBuildTargetGroup)
and you think it is dangerous expectation?
But if this API compatibility would be broken, I would prefer braking compilation instead of blindly returning 4 or 6 without checking.

**Comment by Feacur** [comment]
No, not at all. I think that it is dangerous expectation that UNITY_3_OR_ANYTHING would support UNITY_5_6_OR_NEWER API. Surely, it's my problem if I do not specify a proper define at all, although.

**Comment by van800** [comment]
https://github.com/JetBrains/resharper-unity/commit/3b1537dce1ba24dc6a11bdea530c3d9ede712801

**Comment by van800** [comment]
Please let me know if it helped

**Comment by Feacur** [comment]
Just tried 3b1537d, this one works and ineed is cleaner. Thank you.
