### ISSUE TITLE
Allow running Unity tests with coverage from command line

### ISSUE THREAD

**Issue by tallior** [JetBrains/resharper-unity#1783]
We are using Rider on our local dev machines for development using Unity.
It supports a built-in test runner (which is a different implementation from Unity's test runner i believe).

This also works with dotCover to provide coverage for tests with Unity. We'd like to be able to execute this from the command line in our CI environment (TeamCity).

Is this scenario supported? I am not sure i fully understand the whole architecture (is Rider using Unity's test runner or did you re-implement the NUnit test runner yourselves? how is coverage supported? Unity must be started using some flag. can i do this manually myself?)

Any words of wisdom will help :)

**Comment by van800** [comment]
Test runner in Rider sends names of tests to Unity.
Our plugin in Unity executes tests and sends results back when they appear.

Scenario on CI is not yet supported, in fact you are first, who asked that. However we will try to look into it in one of future iterations. Thank you for the request.

When we tried running our own integration tests with Unity, we were surprised that using Free Unity license for CI requires manual activation. Since all our agents are cloud on-demand instances, we haven't yet solved this problem.

**Comment by tallior** [comment]
The only reason i am interested in this, is that Unity's support for code
coverage requires Unity 2019.1 or higher.

DotCover claims its supported on 2018.3 and higher, which made me wonder
how that is actually achieved. It requires the editor restart  not sure
why, but if we could somehow do that on our CI environment, we could run
tests and measure coverage without upgrading to the newer Unity version.

**Comment by tallior** [comment]
@van800 the corresponding YouTrack issue is marked as fixed: https://youtrack.jetbrains.com/issue/DCVR-10117

How can i test to see if this is working ?

**Comment by van800** [comment]
Answered in https://youtrack.jetbrains.com/issue/DCVR-10117#focus=Comments-27-4600672.0-0
