### ISSUE TITLE
Multiple Issues on Mac with Rider 2020.2 and Unity 2018.4.26f1

### ISSUE THREAD

**Issue by TomWor** [JetBrains/resharper-unity#1797]
I'm trying to get Debugging Unity projects from Rider working for the first time.
Opening the solution and Intellisense all works fine.

I've installed and updated the Rider plugin in Unity but whenever I run "Attach to Unity Editor & Play" and the game starts playing in the Editor, the only thing I can see are Threads and Frames in the Debug Panel, not the SceneTree and the output I get also only works on pause. In the Unity panel, I also don't get any Console output.
When in Rider, the performance of the Unity Editor game window drops from 60fps to 10fps.
When I go to Unity after starting the Debugging process on Rider, Unity sometimes beachballs/crashes.

I've restarted both Unity and Rider several times, issue remains.

Console says:
```
Input/Output redirection disabled: Debugger is attached to an already running process
"/Users/tomwor/Library/Application Support/JetBrains/Toolbox/apps/Rider/ch-0/202.6397.244/Rider.app/Contents/lib/ReSharperHost/macos-x64/dotnet/dotnet" exec "/Users/tomwor/Library/Application Support/JetBrains/Toolbox/apps/Rider/ch-0/202.6397.244/Rider.app/Contents/lib/ReSharperHost/JetBrains.Debugger.Worker.exe" --mode=client --frontend-port=53838 "--plugins=/Users/tomwor/Library/Application Support/JetBrains/Toolbox/apps/Rider/ch-0/202.6397.244/Rider.app/Contents/plugins/rider-unity/dotnetDebuggerWorker"
```

**Comment by van800** [comment]
Hi @TomWor, I have reread the report couple of time, but still can't figure it out.
Could you please try to clarify the report like:
1. Your setup (Unity version, Rider version, OS)
2. Steps to reproduce
3. Expected result
4. Actual result
Adding some project on which the issue reproduces may also help.

Thank you!

**Comment by TomWor** [comment]
1. Setup: Unity 2018.4.26f1 + Rider 2020.2 + Mac OS 10.15.6 (Catalina)

2. I open Unity, log tells me Rider plugin initialized (verbose output), I click a C# file, it opens in Rider.
I click on the Icon "Important Unity related actions" and select "Attach to Unity process".
I select the process. I then get the message "Input/Output redirection disabled: Debugger is attached to an already running process" in the Rider Console. I press "Play/Edit" in Rider, my game starts in the Unity editor.
I go into the Rider debugger Tab and press "Pause". I then get a List of Threads and Frames in seperate tabs from Unity like WaitHandle.XXX in System.Threading, mscorlib.dll. I click through all of them.

3. Expected result: Find the "SceneTree" variable in any of the threads.

4. Actual Result: No entry for SceneTree present.

I do get the Unity Console output in the "Unity" tab now.

**Comment by citizenmatt** [comment]
What happens if you add a breakpoint? Hitting the debug pause button will stop the code at the currently executing point, and there is no guarantee that any of your script code is currently executing. Pause is only really useful if you have script code that is executing for a long time, i.e. several seconds, and you need to break execution manually to see what's going on. It's usually better to set a breakpoint so that the code will stop at a known location.

All the messages and everything else you see are expected and appear to be good. "Input/Output redirection disabled" is a normal message - it means the Unity editor was already executing and the debugger has attached to rather than started the process, so it's not possible to capture output (e.g. the output from `Console.WriteLine` if this was a console app). Pausing the debugger and being able to see threads and frames is also good - you're attached to the editor and the debugger can see what's going on. But any executing script should be on the main thread, and should be selected by default - if you don't see any known code, then nothing is currently executing.

**Comment by TomWor** [comment]
Thank you, with breakpoints it works.
I had been under the impression the pause function would allow me to inspect the SceneTree in a more manual way, don't know where I got that. 

The breakpoints are an impressive feature with conditions and such, will more than suffice for all my debugging needs.
