### ISSUE TITLE
C# Project File names not generating correctly

### ISSUE THREAD

**Issue by Rennan24** [JetBrains/resharper-unity#180]
Not sure if this is an issue with they way Unity communicates with Rider or with how Rider or something else, but whenever I make click open C# project in Unity with Visual Studio as the default IDE it creates the correct Assembly name such as `ProjectName`, `ProjectName.Editor`, `ProjectName.Plugins`, but when I open it up in Rider it calls the C# Projects `Assembly-CSharp`, `Assembly-CSharp-Editor`,  and `Assembly-CSharp-firstpass` even though the solution file is still ProjectName.sln. 

And even if I change the `UNITY_PLAYER_PROJECT_NAME` and `UNITY_EDITOR_PROJECT_NAME` strings inside of the Unity3DRider plugin that gets put inside Unity the project names still come out as `Assembly-CSharp` Not really a big deal since I don't spend a lot of time in the solution explorer and I can just press shift twice to get to the file that I need to go to, but it is kind of weird that this behavior happens.

And I just want to say, thank you guys for this great plugin and keep up the great work! :D

**Comment by van800** [comment]
Hi! Thank you for using Rider! )
Actually VS in Unity has some special solution-project generation.
And nearly all other tools get monodevelop-like generation.
Constants in Unity3dRider plugin are not used to set the dll name and project name, but just to get those names.

Maybe it is possible to alter the generation process and edit sln to show different names in SolutionExplorer, but it may lead to confusion because dlls and csproj files will still have names like `Assemly-CSharp`.

Let me know if I haven't got your point correct.

**Comment by van800** [comment]
It might be a good idea to file a request to Unity team with comparison of generation results for VS and MonoDevelop.

**Comment by Rennan24** [comment]
Oh I see now, thanks for clearing all that up for me, glad to at least know it wasn't something that was bugged on my end haha!
