### ISSUE TITLE
Add support for including Roslyn analyzers in Unity projects

### ISSUE THREAD

**Issue by tallior** [JetBrains/resharper-unity#1835]
I would like to start using code analysis from other 3rd party providers (these are mostly distributed as .DLLs or via NuGet).

The main problem with Unity is that it auto-generates its .sln and .csproj files, so any changes made by importing something from NuGet are lost whenever you recompile the code.

Is there any way that this scenario could be supported? (e.g: this plugin would somehow patch the generated .csproj files to include this information?)

**Comment by van800** [comment]
Depends on Unity version, which one you have?

**Comment by tallior** [comment]
I am on 2018.4.0 at the moment, planning to upgrade in the near future if
that helps (but i would love to be able to use it with this version as well)

**Comment by van800** [comment]
For Unity pre-2019.2 this is likely the best approach:
https://rider-support.jetbrains.com/hc/en-us/community/posts/360002398539/comments/360001394920

For newer Unity 2019.2+ there is also csc.rsp support https://github.com/JetBrains/resharper-unity/issues/1337

**Comment by JesseTG** [comment]
The problem is that using `csc.rsp` to add analyzers *considerably* slows down editor iteration. I don't need Roslyn analyzers to run within Unity, I only need them to run within Rider. Even then, I don't need Roslyn analyzers to run universally (for example, I don't want them to run on third-party packages).

**Comment by van800** [comment]
@JesseTG what Unity version are you using?

**Comment by JesseTG** [comment]
> @JesseTG what Unity version are you using?

Unity 2020.1.6f1, on Windows 10 with Rider 2020.2.3.

I use Roslyn analyzers in my project very liberally, which is why I'd like to have fine control over when and where they actually run. For example, I only want the [NUnit analyzers](https://github.com/nunit/nunit.analyzers) to run on the assemblies that actually use NUnit.

**Comment by van800** [comment]
@JesseTG 
You can use approach from https://rider-support.jetbrains.com/hc/en-us/community/posts/360002398539-Use-StyleCop?page=1#community_comment_360001394920
with Condition-s like:

```
<Project>
  <PropertyGroup Condition=" '$(ProjectName)' == 'MyProject' ">
    <CodeAnalysisRuleSet>$(MSBuildThisFileDirectory)analyzers.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
</Project>
```

**Comment by JesseTG** [comment]
@van800 Given that Unity's `.csproj` files are auto-generated, how can I be sure that your proposed solution won't vanish under my feet?

**Comment by van800** [comment]
@JesseTG Directory.Build.props is not autogenerated, you may write whatever you want there.

**Comment by JesseTG** [comment]
> `Directory.Build.props` is not autogenerated, you may write whatever you want there.

Really? Huh. Where should `Directory.Build.props` go, in the project's root?

**Comment by JesseTG** [comment]
Hot damn, this works like a charm! It gives me all the analysis I want without excessive slowdown and without cluttering my repo with DLLs! I will probably go overboard on this very quickly.
