### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by ZhouJiaZhi** [JetBrains/resharper-unity#1861]
Looking at the picture below, he prompts that this variable must be true, but this variable can actually be false
<img width="1025" alt="截屏2020-09-26 16 49 07" src="https://user-images.githubusercontent.com/20750357/94336799-5f1ec800-0018-11eb-9abe-144bfb645d5f.png">

**Comment by citizenmatt** [comment]
This is saying that the expression is always true, rather than the variable. At this point in the code, we know that `isEndPointInSquare` must be false - if it were true, the first `if` statement would catch it. Because we know that it's false, we know that `!isEndPointInSquare` is always true _at this point in the code_. That's what the message is telling us.
