### ISSUE TITLE
Mark methods with MenuItem atribute as used

### ISSUE THREAD

**Issue by dantreble** [JetBrains/resharper-unity#19]
http://imgur.com/aEwEMAj

http://docs.unity3d.com/ScriptReference/MenuItem.html

Thanks!

**Comment by aybe** [comment]
It's now four years later but this is still happening:

![devenv_2020-06-14_15-44-39](https://user-images.githubusercontent.com/1537591/84595018-fab76e80-ae55-11ea-89e2-df88d6b5b60e.png)

Unity 2020.2.0a13.1691
Unity Support 2020.1.0.179
Resharper 2020.1.3
Visual Studio 16.6.2

Thank you

**Comment by citizenmatt** [comment]
This isn't what I'm seeing. A private method is marked as unused, but it's Visual Studio doing that, and there's not much we can do to fix that. Your screenshot is showing that ReSharper thinks it's unused, but mine shows that ReSharper thinks it's in use - you can see the Roslyn icon in the Alt+Enter menu.

<img width="444" alt="Screenshot 2020-06-14 at 5 14 51 pm" src="https://user-images.githubusercontent.com/222659/84598434-9cdd5380-ae62-11ea-88a0-e943ebf93ef5.png">

Can you confirm that the Unity Support plugin is working elsewhere? Do you see "Unity event functions" in the Generate method, for example?

Also, this wasn't with exactly the same version of Unity. Can you confirm that the attribute is still called `MenuItem` and not `MenuItemAttribute`? Ctrl+Click to navigate will confirm.

**Comment by aybe** [comment]
I confirm that indeed it is the right attribute.

Also, the plugin does work as for instance, I can generate Unity event functions.

And the screen you've posted is intereseting to say the least, I've never seen that magnifier icon along those squiggles on light or wrench.

I don't know what's going on, maybe something's wrong on my side.

**Comment by citizenmatt** [comment]
You get the magnifier if you use the alt+enter keyboard shortcut, while clicking the icon in the text gutter doesn't show it (the idea is that the magnifier icon is a hint that you can click + search, or just start typing to search. TBH, I don't get why it's not shown on click too).

The squiggles on the lightbulb and wrench are the Roslyn logo, and indicate that these actions come from Visual Studio, rather than ReSharper.

Can you show the Quick Doc for the `MenuItem` attribute? It should show the attributes that are applied to it, including the external attributes added by the plugin. You should see something like this, with `[MeansImplicitUse]` (the attributes might be collapsed as `[…]` - click to expand).

<img width="444" alt="Screenshot 2020-06-14 at 10 57 57 pm" src="https://user-images.githubusercontent.com/222659/84605119-c910c880-ae92-11ea-9e74-92fa72f0611e.png">

**Comment by aybe** [comment]
Okay it so obvious that I did manage to not see it during all this time, indeed the magnifier is present !

Now I think we're getting closer to the problem, `MeansImplicitUse` is nowhere to be seen for me:

![devenv_2020-06-15_11-33-50](https://user-images.githubusercontent.com/1537591/84641986-23923f00-aefc-11ea-8300-5b333ae426fd.png)

But the attribute exists ... and I use attributes from Unity assemblies. Actually I've even tried to copy custom annotations implementation but they are simply ignored as `using UnityEditor` will import Unity's ones and therefore hide custom annotations.

**Comment by citizenmatt** [comment]
Hang on, that popup says that `MenuItem` is defined in `UnityEditor.CoreModule.dll` - that looks new! I guess they're splitting the UnityEditor assembly up into different modules now. That would explain why you're not seeing this - the external attribute is only defined for the `UnityEditor.dll` assembly.

I'll see if I can get some more details on this.

**Comment by aybe** [comment]
Alright, great !

That's funny how each other can have different setups and get so much different results 🤣.
