### ISSUE TITLE
"External documentation" action doesn't work

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#190]
Ctrl+F1/Shift+F1 does nothing.
Button in QuickDoc window is disabled.
![image](https://user-images.githubusercontent.com/1482681/28813750-f128f30c-769a-11e7-8904-ac55849241f8.png)
Reported here https://rider-support.jetbrains.com/hc/en-us/community/posts/115000490690-Unity-Scripting-Reference

**Comment by citizenmatt** [comment]
This is a Rider platform issue - Rider's own QuickDoc implementation doesn't support navigating to external documentation. I've raised an issue ([RIDER-8241](https://youtrack.jetbrains.com/issue/RIDER-8241)). There might be a workaround, I'll take a look.

**Comment by citizenmatt** [comment]
BTW, that screenshot should have a "summary" comment for `MonoBehaviour`, but that requires UnityEngine.xml to live next to the UnityEngine.dll - can you check to see if it's there? As far as I've seen, Unity itself will make sure that either you reference the assembly in the standard install, and the xml file is there, or it will reference in Library, and make sure the xml file is there, too.

**Comment by van800** [comment]
@citizenmatt Yes, I am on linux and there are no dll.xml in Unity.

**Comment by van800** [comment]
What about the direct calling External Documentation on symbol in TextControl? It also doesn't work.

**Comment by citizenmatt** [comment]
What do you mean?

**Comment by van800** [comment]
I added the request
https://youtrack.jetbrains.com/issue/RIDER-8245
Repro:
Put caret at MonoBehaviour and call "External Documentation" action.

**Comment by van800** [comment]
It seems I was expecting different behaviour from "External Documentation" action.
Maybe we can add a new shortcut, which will allow opening Documentation in Browser?

**Comment by van800** [comment]
Same requested here https://github.com/JetBrains/resharper-unity/issues/98

**Comment by citizenmatt** [comment]
Yep, these two are symptoms of the same problem ([RIDER-8241](https://youtrack.jetbrains.com/issue/RIDER-8241)). Rider doesn't support external navigation, so the _External Documentation_ button and keyboard shortcut (which do the same thing) are unavailable.

The problem is that IntelliJ and ReSharper do different things - IntelliJ is expecting a URL to navigate to, while ReSharper's _Read More_ link is not a URL, but an action that causes ReSharper to display either product help, or invoke Visual Studio's MSDN keyword search. This plugin intercepts the MSDN request for Unity specific types and opens either local help, or a search page on the Unity site. This is too decoupled for Rider to know about in this context. I suspect it will require a change to ReSharper's API to fix properly, but I'm still looking into a workaround.
