### ISSUE TITLE
Cannot find a declaration to go to

### ISSUE THREAD

**Issue by cimbis** [JetBrains/resharper-unity#2049]
Hi there!

Just started to work on my very first Unity (2020.3.0f1) project.

Am running macOS 11.2.3 (20D91), dotnet bundled together with Rider 203.7717.10 and Mono JIT compiler version 6.12.0.122.

Settings in IDE as follows:
![Screenshot 2021-03-20 at 11 10 54](https://user-images.githubusercontent.com/5424191/111864985-f41dd080-896c-11eb-8f89-c2007d67e60d.png)

My Unity project:
![Screenshot 2021-03-20 at 11 06 06](https://user-images.githubusercontent.com/5424191/111864911-7063e400-896c-11eb-8389-24850e5f9e64.png)

And the error in my IDE:
![Screenshot 2021-03-20 at 11 06 28](https://user-images.githubusercontent.com/5424191/111864912-73f76b00-896c-11eb-8515-fc6938652388.png)

Seen similar issues on JB forums, where there was a suggestion to invalidate cache - didn't help.

Here are the logs:
[rider-logs-20210320-104631.zip](https://github.com/JetBrains/resharper-unity/files/6175176/rider-logs-20210320-104631.zip)

Hope to see a solution for this issue soon.

Thanks,
JC

**Comment by citizenmatt** [comment]
You looks like you've opened the Unity project as a folder in Rider, rather than as a C# project. Rider doesn't have any information about the project, such as what Unity assemblies you're using, etc. And so can't provide any features like navigation.

Make sure you've selected Rider as the default External Tool in Unity's settings and double click on a C# file in Unity. Unity will generate project files for Rider to open, and Rider will then be able to do navigation, code completion, etc.

**Comment by cimbis** [comment]
@citizenmatt That did the trick! 
Although Rider did open automatically once I clicked on .cs source file in Assets, Rider was not set as default external script editor _explicitly_. Once that was done, declaration files are now found by the IDE! 👌

**Comment by citizenmatt** [comment]
Great! Glad it's working.
