### ISSUE TITLE
Roslyn Analyzer support under packages

### ISSUE THREAD

**Issue by nowsprinting** [JetBrains/resharper-unity#2087]
Roslyn Analyzer is now supported in Unity 2020.2. As of Rider Editor v2.0.7, a DLL labeled "RoslynAnalyzer" is added to the .csproj as <Analyzer> node.

If the DLL is under Assets/ or Packages/ (Embedded Package), it works as expected.

But, Specify file path (Local package) or imported from the UPM registrar do not work.
This is because the path in <Analyzer> node is pointing under Packages/ and there is no DLL entity there.

We would like to include the analyzer in the UPM package and distribute it.

**Comment by van800** [comment]
related to https://forum.unity.com/threads/support-roslyn-analyzers-in-unity-projects.927437/#post-7123724

**Comment by van800** [comment]
Thank you for bringing this up. I tried reproducing and for me it works only when analyzer is in the Assets. As you wrote in the forum - under Packages "it is not possible to set the "Asset Label" in the Plugin Inspector window".
It is very likely that this can only be fixed on Unity side, I have notified them about the use-case and I hope it would be addressed soon.

I am closing this issue for now, because there is nothing we can do.

**Comment by nowsprinting** [comment]
It behaves differently from my environment. But that's ok.

I understood the current situation is that Unity doesn't seem to support analyzers under the Packages folder (doesn't in the documentation), and the Rider Editor is adapting to that.
