### ISSUE TITLE
Unity.UnknownLayer inspection does not respects default Unity layers

### ISSUE THREAD

**Issue by DmitriyYukhanov** [JetBrains/resharper-unity#2094]
Hey, looks like this inspection does not takes standard Unity layers into account:
![image](https://user-images.githubusercontent.com/883587/119202382-52644e00-ba99-11eb-8391-a3771c494e45.png)

![image](https://user-images.githubusercontent.com/883587/119202480-89d2fa80-ba99-11eb-92cf-eda684a12f71.png)

**Comment by krasnotsvetov** [comment]
Hi!
Could you attach your `\ProjectSettings\TagManager.asset` file?

**Comment by DmitriyYukhanov** [comment]
Hey @krasnotsvetov , sure:
[TagManager.zip](https://github.com/JetBrains/resharper-unity/files/6592413/TagManager.zip)

**Comment by citizenmatt** [comment]
What version of Unity is this project?

**Comment by DmitriyYukhanov** [comment]
> What version of Unity is this project?

It's Unity 2018.4.0f1 %)

**Comment by DmitriyYukhanov** [comment]
I've just tried updating project to Unity 2019.4.0f1 and still seeing this though.

**Comment by DmitriyYukhanov** [comment]
Also I can't reproduce this issue in new project both in Unity 2018.4.0 and 2019.4.0, it's something specific to my project.

**Comment by citizenmatt** [comment]
I think you have a project that was created in a much older version of Unity, and you haven't edited tags/layers since then. I suspect if you add a new tag, it will save in the new format. If I look at a file in the format we do support, it's also got a `serializedVersion: 2` field. I'm guessing yours was the original format, but I can't recreate it with 5.6, so it much be earlier than that.

**Comment by DmitriyYukhanov** [comment]
Yes, it's totally possible it migrated from 5.4 or even earlier version!

**Comment by citizenmatt** [comment]
Either way, I've just added support :)
