### ISSUE TITLE
Rider doesn't fully support ShaderLab syntax highlight

### ISSUE THREAD

**Issue by VirtualMaestro** [JetBrains/resharper-unity#216]
Hello,
Plugin page [https://github.com/JetBrains/resharper-unity](https://github.com/JetBrains/resharper-unity)
 says that it supports syntax highlight (at least) of ShaderLab for Rider. But for me, it just partially supports highlighting, not to mention auto-completion (it doesn't work completely).
I checked for ReSharper and it fully works with highlights and auto-completion.
I'm using Rider version 2017.1.1. (Of course, 'Unity Support' plugin is installed)
I've attached screenshot how it looks like.

Thank you 
![shaderlab_highlight_issue](https://user-images.githubusercontent.com/426870/29818608-5dfef0de-8cbd-11e7-830a-ddfd600aacce.jpg)

**Comment by IvanPashchenko** [comment]
@VirtualMaestro It is a known issue, we've not implemented full ShaderLab support in Rider yet. We're working on it — it is the most important feature for us now.

**Comment by VirtualMaestro** [comment]
I see. I thought I've setup something wrong.
Thank you

**Comment by bradzoob** [comment]
So, another year later, are we there yet?

**Comment by lucasmontec** [comment]
Please?

**Comment by apouche** [comment]
> it is the most important feature for us now.

2 years later, still basic support.

**Comment by adamgit** [comment]
Yep. Can't even indent the code correctly. Basically dead.

**Comment by parodyband** [comment]
rip

**Comment by nrebei2** [comment]
Nothing?

**Comment by citizenmatt** [comment]
We're very much aware that Rider's support for Cg is far from ideal, but it is being worked on. Unfortunately, support for Cg, which is a language very similar to C/C++ especially in its use of preprocessor macros, is dependent on several other features and architectural changes that are also in progress. We're hoping to have something soon, but unfortunately, we don't really have anything we can talk about right now. I get this is frustrating - sorry it's taking so long.

**Comment by billbai0102** [comment]
Any updates? Been waiting 3 years for .shader support in Rider, and still nothing : (

**Comment by citizenmatt** [comment]
Nothing I can add right now, sorry. We get that this is a pain point, and a missing piece in our Unity support. We're working on it.

**Comment by adamgit** [comment]
For what it's worth ... this missing feature is the main reason I'm cancelling JB subscription - I've been testing and found that Rider2018 is 100% fine for Unity developemnt, I don't even need to move to a different IDE. With 8 weeks of trialling this, I found that Rider2019 had added almost nothing for Unity developers.

We're basically paying for this to NOT happen (the last 12 months of Rider updates have had very little impact on Unity development, unless you are a junior coder [How many professional C# devs need a popup telling them that Update is "probably called quite often"? :) ]).

At Unite Copenhagen, the promise of a possible quick-fix for this kept me hanging on -- and I *know* how effective and relatively simple that quick-fix is, I've worked on IDE dev teams before. The fact that it didn't happen screams that there's serious internal problems with JB dev / codebase (this stuff is many times simpler than JB pretends it is - its' not being held back by tech problems, it's being held back by corporate/internal/strategic problems).

That's fine....except: it very strongly implies that you're not going to fix this within a 2-4 year timeframe. Which makes it insane for any real developer to carry on using your IDE *and paying for it to NOT be updated*.

Sad panda :(.

**Comment by adamgit** [comment]
PS: I spent a few weeks using current rival C# editors, and here's the saddest part: Rider2018 was *still* a better overall day-to-day experience than any of them (although the others win on more advanced features, or performance in some cases - so JetBrains is losing ground - but Rider *used to be* the go-to editor for Unity/C#).

But at the current rate I expect by this summer/autumn that will have changed and Rider won't be in the top 3 options for Unity/C# any more. Which is a shame because in a lot of ways it is/was really good, and I wish JB had been able to stick with it instead of sidelining Unity devs.

**Comment by adamgit** [comment]
Last comment (I promise):

"We're very much aware that Rider's support for Cg is far from ideal"

Wat.

There is ZERO SUPPORT in Rider. Not "far from ideal". But, instead, literally NONE! I get more features for shader editing in a non-programmers text-editor than I do in Rider! (text editors at least do consistent line-indenting, which Rider still cannot/will not attempt).

Statements like that one are what have convinced me this simply isn't on JB's strategic plan: Rider is not intended to be used by Unity developers, and we should stop using it.

**Comment by lucasmontec** [comment]
This doesn't make any sense. Please avoid such comments on a git issue. If
you are unsatisfied with the product, complain on their site man. This is a
place for talking about issues and features.

Also, rider 2019 did a lot for unity devs. They now fix asset files for
name changes. I'd pay Rider just for that. Rider is not losing ground just
because it doesn't have a feature no other editor provides. Anyway, keep
personal issues out of github.

**Comment by nrebei2** [comment]
Other editors do have support for shaders.

**Comment by lucasmontec** [comment]
This is not the point, if other editors support shaders than use other
editors. This is about Rider and its development.

**Comment by citizenmatt** [comment]
As mentioned above, we are working this. The first step to great Cg support is to get C/C++ into the platform, which we are doing with [Rider C++ and support for Unreal](https://www.reddit.com/r/unrealengine/comments/e1wgjc/jetbrains_is_working_on_rider_c_for_unreal_engine/). This gives us a platform to extend the C tooling to understand Cg. But it also requires a lot of work to bring a product designed to run on Windows inside Visual Studio to run cross platform on Mono and .NET Core as part of Rider. It's in progress, but I don't have anything concrete to share right now. As soon as I do, I will - we want to get shader support into the product too.

**Comment by bradzoob** [comment]
*wind swept ruins of a post apocalyptic city in the 29th century*
A single, gaunt figure can be seen crawling across the smashed concrete, ravaged by time and searing heat; it halts. The figure looks up, straining to see through a comedy of hair weaving dark shadows across it's face, it croaks the words; "how close to working HLSL/CG syntax support are we"?

Roadmap for release schedule for this would be Epic also.

**Comment by citizenmatt** [comment]
We've [just announced initial HLSL support in ReSharper C++](https://blog.jetbrains.com/rscpp/resharper-cpp-2020-1-eap-hlsl/). As mentioned above, ReSharper C++ is coming to Rider, so we'll see this tooling adopted in Rider for Unity, too. It's not going to be part of Rider 2020.1, but if we can get everything synced up correctly, we should see it in Rider 2020.2.

**Comment by anastasiak2512** [comment]
FYI, we've just started [Rider for Unreal Engine Public preview](https://www.jetbrains.com/lp/rider-unreal/). It includes basic C++, specific UE4 and also HLSL support.

**Comment by makmatics** [comment]
Any leads yet?

**Comment by parodyband** [comment]
bump

**Comment by FoxWareFX** [comment]
So there are some updates about shader support for Rider?

**Comment by citizenmatt** [comment]
Oh wow, sorry, this issue should have been updated a while ago. I guess it got missed with it being closed.

Rider has rich support for shader files as of Rider 2020.2. There's a full language service for HLSL in standalone files and `.shader` files. It has syntax highlighting, error highlighting, code folding, completion, navigation, inspections and refactorings.

**Comment by PalashBansal96** [comment]
@citizenmatt Hello, HLSL support works great for files in a Unity project, but for standalone files or files that are explicitly not in a Unity project, only basic tokens are highlighted. (even float2, float3) doesn't work, even when the plugin is enabled. 
Is there any way to enable this?

**Comment by citizenmatt** [comment]
Unfortunately not. The way Rider/ReSharper work with language files is that they need the context of the project to allow things like resolving location of default includes (which define a lot of the symbols and macros needed to make sense of the rest of the file) and also define default symbols.

**Comment by PalashBansal96** [comment]
Just wondering, with the Rider for unreal coming up, are you guys making a separate backend (from Unity shaderlab) for HLSL and CG support there or some kind of generic plugin that's enabled in all kinds of projects. 

Plus for basic syntax highlighting like primitive types, function calls, basic navigation, etc what is the need of the context of the project?

**Comment by citizenmatt** [comment]
The shader support in Unity comes from the work in Unreal, so technically, it's the other way round 😁. Rider for Unreal got shader support first, because it's all based on the C/C++ tooling, with support for includes, macros, etc. (It's also why shader support took so long, as we've been working to integrate the C/C++ tooling into Rider, including making it work cross platform). We then made it possible to reuse the shader support in Unity, such as support for default includes and also to host the HLSL language inside the ShaderLab language, so we can have little "islands" of HLSL code inside another file as well as in a standalone file. That's what we've got today in Unity.

Most features require a project context to provide any value. If we don't have a project context, we can only resolve the symbols that are defined in the current file and this provides so little value that it's not worth building the support for it. E.g. a C# file that uses `Console.Out` needs to have some context to point us to `mscorlib.dll` and others in order to find `System.Console`. If don't have that, we can't provide code completion, parameter info, type inferencing (`var`) and so on. So we pretty much always require a project context of some description.

A shader file might be more standalone than a C# file, but it still requires extra context. E.g. various `.cginc` files are automatically included, and we need to know which version of Unity to include them from. Also various symbols are defined before we do parsing, build a semantic model and run analysis. Interestingly, `float2`, `float3`, etc. are simple typedefs automatically added by the engine, but again, it's an engine that expects that project context, so it's not available standalone.

I think it really boils down to the fact that a project context is needed for the overwhelming majority of features, so the app is mostly architected to require a project context.

**Comment by skiwee45** [comment]
Hello, just got rider recently, I'm having the same issue as the post author, but supposedly this was fixed already. When I go to settings I can see the color scheme for Cg/HLSL but in .shader file it only highlights shaderlab and inside the HLSL block CGPROGRAM ENDCG there is little to no syntax highlighting. Is there some settings that I am missing? 
![image](https://user-images.githubusercontent.com/35319578/128436132-46f73f7d-b2e1-446b-b545-cd5d274a40a9.png)

**Comment by citizenmatt** [comment]
@jamesplease there aren't any immediate plans to work on ShaderLab, but Rider should already be working well with the HLSL language blocks in `.shader` files and `.hlsl`, `.cginc`, and so on. This should give you completion, navigation, highlighting and so on for the HLSL language. If you're not seeing this, make sure the `.shader` file is included in the `.csproj` file - these files need to be in a project so that we know what project context is being used, so we can find Unity installs to find default headers and so on.

Support for the ShaderLab syntax itself is still pretty basic, to be honest. There's syntax highlighting, and error highlighting for simple syntax errors. There's completion for property names and navigation, and we should also reformat on cleanup. However, that's about it. There's no completion for keywords, or tag names, and the auto-formatting as you type needs work. While we're not expecting to get to this during the 2023.1 release, I think we need to take a look for 2023.2

**Comment by citizenmatt** [comment]
The `.csproj` entry looks fine to me. I'm not quite sure what's going on with the auto-complete. It appears to be correctly parsing include files to get those defines, so I'm not sure why other symbols aren't listed. This looks like a separate issue to the original post, which has been closed - could you create a new issue so we can track it a little easier, please?
