### ISSUE TITLE
Would you update this extension to ReSharper 2021.3?

### ISSUE THREAD

**Issue by PoisonerSC** [JetBrains/resharper-unity#2230]
I updated my reshaper to 2021.3.1 but I didn't found this in Extension Manager.
Would you update this to latest resharper version?

Btw, I installed this extension on old resharper version before. Extension Manager noticed me that occurred 6(or 7 I didn't remember clearly) errors every time. But it seems working well. Is this normal?

**Comment by citizenmatt** [comment]
Yes, it's coming. Unfortunately, there was a ReSharper specific bug that didn't get found until too close to release, but it should be fixed and pushed in the next couple of days, hopefully sooner.

As for install errors, this is likely related to #1816. The Unity plugin requires ReSharper C++ to be installed, as its shader support is based on C++ and the installer will show errors in this case. AIUI, most features still work, apart from shader support. If you use the ReSharper installer to add C++, then you'll also get highlighting, completion, inspections, refactorings and so on for shader code.

**Comment by PoisonerSC** [comment]
That's great! I'm looking forward to your update.
I'll install ReSharper C++ before install the plugin next time.
Thank you very much. Wish your work going well.

**Comment by sonnybsj** [comment]
Unity Support is now available in the Extension Manager. See [Versions](https://plugins.jetbrains.com/plugin/11629-unity-support/versions)

**Comment by citizenmatt** [comment]
Hi all. After investigating the ReSharper specific bug, it turned out not to be a showstopper, and I uploaded the [2021.3.0 build](https://plugins.jetbrains.com/plugin/11629-unity-support/versions/stable/151372) about a week ago. I've just uploaded the [2021.3.2 build](https://plugins.jetbrains.com/plugin/11629-unity-support/versions/stable/152123), which fixes this particular exception (in the `.asmdef` editor), and a couple of other minor fixes too.
