### ISSUE TITLE
public SerializeField with private set is marked as unused

### ISSUE THREAD

**Issue by leohilbert** [JetBrains/resharper-unity#2319]
Hi, I spent some time searching through existing tickets, but didn't find an open issue for this yet. I hope I didn't miss one!

Unity supports to add a public property where the internal field is marked as a "SerializeField". That way you don't need to create a backing field and save one line. 🎉 
![image](https://user-images.githubusercontent.com/2004063/169230539-5e08dbd7-64f3-4db5-9ebb-17450998946b.png)

This would be equal to 
```
[SerializeField] private ConPlayerParentController playerParent;
public ConPlayerParentController PlayerParent => playerParent;
```

However Riders marks the "private set;" as unused, although Unity uses it, because it's a SerializeField.
Would be great if that would be fixed, or if there's a way to manually tell rider to ignore usage checks when a field is marked with "SerializeField".

Thanks! 😺 

Edit: FormerlySerializedAs also doesn't seem to be added on renaming. 🤔 

Rider Version 2022.1.1

**Comment by van800** [comment]
Related to https://youtrack.jetbrains.com/issue/RIDER-77782/ReSharper-Unity-plugin-should-ignore-unused-property-set-accesso

**Comment by citizenmatt** [comment]
As for `FormerlySerialisedAs`, it won't apply in this case because you've renamed a property, not the serialised field. The name of the serialised field is generated, based on the property, but will have a value like `<PlayerParent>k__BackingField`. In order to apply the `FormerlySerialisedAs` attribute, we'd have to use the same generated name, and this is undocumented behaviour, and not guaranteed to be the same between versions of the compiler (it has stayed the same, and likely will, but I'd rather not take dependencies on undocumented behaviour unless we have to)
