### ISSUE TITLE
The type or namespace name 'TMPro' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by drew-fc** [JetBrains/resharper-unity#2377]
hi,

I keep getting this error, that will sometimes go away randomly. (Unity 2019.4.0F, Rider latest version 2022.3)
For whatever reason, Rider can't find TMPro.

If I open the solution in Visual Studio, VS allows my to right click->Add Reference-> Unity.TextMeshPro.dll and the error disappears.
How can I add the reference from Rider?
This seems to go away randomly if I delete the CSProj and SLN files, but then it comes back.
This makes Rider un-usable in my project, which is unfortunate because it has a superior interface to Unity otherwise.

thanks,

**Comment by van800** [comment]
While working with Unity, keep in mind that csproj files are generated by Unity to help the IDE. It doesn't work the other way around. There is no use to edit the csproj, Unity doesn't use it for compilation.

You may try to close unity, do the code editing, open Unity. Close the IDE. Start Unity, it would show compilation errors. Try to use Unity documentation or TMPro documentation to fix the references. Once they are fixed in unity, you would also see that Ide would stop showing those errors.
