### ISSUE TITLE
Shader PackageRequirements block not recognized

### ISSUE THREAD

**Issue by Quriz** [JetBrains/resharper-unity#2408]
When adding the [PackageRequirements](https://docs.unity3d.com/2021.2/Documentation/Manual/SL-PackageRequirements.html) block to a shader, Rider doesn't recognize it.

![image](https://github.com/JetBrains/resharper-unity/assets/75581292/d33c7cdd-fe92-4fca-80f0-46909f747ad0)

**Comment by citizenmatt** [comment]
Fixed in 2023.2 as part of [RIDER-94416](https://youtrack.jetbrains.com/issue/RIDER-94416). See https://github.com/JetBrains/resharper-unity/commit/88c563237b1afc56e825e47ab4af69a391a0bdd0. It should already be in the 2023.2 [Early Access Preview](https://www.jetbrains.com/rider/nextversion/) builds.
