### ISSUE TITLE
ReSharper doesn't display documentation for packages

### ISSUE THREAD

**Issue by aybe** [JetBrains/resharper-unity#2417]
Although members documentation is present on most packages, ReSharper is not able to show it.

For example, Burst:

Mouse hovering shows nothing:

<img width="299" alt="image" src="https://github.com/JetBrains/resharper-unity/assets/1537591/4d2f1ee0-0327-4b8d-ba27-9a9752969134">

Ctrl-Shift-F1 shows nothing as well:

<img width="296" alt="image" src="https://github.com/JetBrains/resharper-unity/assets/1537591/9df7f550-ed1a-4f35-b830-cc3a4a4381a3">

Currently, one has to press F12 to decompile the code to manually look at the documentation, quite unpractical.

Any way this can be solved?

**Comment by citizenmatt** [comment]
Unfortunately, it's a Unity problem. Packages are compiled into assemblies and referenced as binary, but it doesn't generate the `.xml` documentation file. Rider and ReSharper therefore don't have anything to display. And since the source files aren't part of the solution, we don't have access to the docs in the source files either. The proper fix is to get Unity to generate xml documentation files when it compiles a package.

**Comment by aybe** [comment]
Alright, thank you.
