### ISSUE TITLE
2017.2.2 installation completed 1 errors ocurred

### ISSUE THREAD

**Issue by friuns2** [JetBrains/resharper-unity#251]
got exception when installing extension from extension manager

https://i.imgur.com/alC4JvJ.png

**Comment by citizenmatt** [comment]
I don't think those errors are related to the Unity plugin. The installer is trying to register ReSharper and various plugins with Visual Studio, and it's failing to load an assembly. But the problem is that the assembly is an old version - 106, where ReSharper 2017.2.2 is 109. This might be related to another plugin - do you have any others installed?

The installer should still have completed the other steps successfully, so you'll probably find that ReSharper works just fine after a restart. If there are any issues, you'll be best to raise them at https://youtrack.jetbrains.com, unless it's obvious that it's related to the Unity plugin.
