### ISSUE TITLE
Rider no longer works with external solution.

### ISSUE THREAD

**Issue by ArtOfSettling** [JetBrains/resharper-unity#265]
Maybe my situation is quite unique, and I've found a solution, but it would be great if your extension took care of this automatically.

1. I build my code not through the Unity Provided solution, instead I've got a manually prepared solution.
2. When attaching to Unity, Rider fails to attach.
3. Rider presents the following error when attempting to attach : 'Cannot read Library/EditorInstance.json - file is missing'

My directory setup is something like the following ....

/unity/AllUnityCrap
/solution/MyCustomBuiltSolution

**Comment by citizenmatt** [comment]
The Rider plugin needs to know the process ID of the running instance of the Unity editor so it can attach and debug. The plugin that we install into the Unity editor (the `Unity3dRider.cs` file) will automatically create the `EditorInstance.json` (later versions of Unity create the file themselves). If you're not working in a Unity controlled project, no-one's going to be creating that file, so we can't find a process ID to attach to.

However, if we can't automatically get the PID, we should display a dialog listing all currently running Unity editors, and allow you to choose. It will display a message like you describe, but it shouldn't stop you connecting. Is this not happening? In fact, without checking, if there's only one instance of the Unity editor running, I thought it would automatically attach anyway.

**Comment by ArtOfSettling** [comment]
It used to work this way, it doesn't anymore unfortunately, on top of that, I can manually migrate my EditorInstance.json file into the appropriate location (not really a solution, I just did it for testing), thereby allowing rider to know which process to connect to, and it connects fine, however breakpoints report : 'The breakpoint could not yet be bound to a valid location'.

Unfortunately I updated Unity, Rider and the Unity plugin at the same time, so I'm not sure which is to blame, I could do a little bit further investigation on my end, if it could help, or I could provide you any logs, projects, etc that exhibit this issue.

Rider Version : 2017.2 : 172.4144.1459
Unity Version : 2017.1.1f1
Unity Plugin Version (less relevant I guess) : 2.1.2.1402
Mono : 5.4.0

**Comment by van800** [comment]
In Rider Run-Attach to local processes - select Unity doesn't require EditorInstance.json.
You may try to change mono in Rider settings to the one shipped with Unity. Let us know if it helps with debugging.

**Comment by ArtOfSettling** [comment]
Little bit of an update on this, it seems to be an issue with mono > 5.0.0 since mono > 5.0.0 generates pdb files instead of mdb files by default.

Rider complains that : 'Old versions of mono don't support pdb files'

**Comment by van800** [comment]
Yeah, I even saw a tricky pdb2mdb workaround for this for VS https://youtu.be/ha3t40GJ0Wo?t=1251
But for Rider it is much easier - just switch to unity mono in Rider settings.

**Comment by ArtOfSettling** [comment]
Unfortunately, this doesn’t work for me, since I’m using c# 6 and above in my external solution.

What I’ve found instead is that when I am debugging I can simply switch Unity into experimental mono 4.6 mode. (This likely isn’t a good idea, but it at least let’s me debug).

I guess there’s nothing you can reasonably do on your end to resolve this issue?

**Comment by van800** [comment]
Have you tried setting TargetFramework for you external library to 3.5?

**Comment by van800** [comment]
I closing this because of no response.

**Comment by WellFiredDevelopment** [comment]
Hello,

Yes, target framework needs to be 3.5, since I’m building a dll to use in Unity.

I didn’t respond because I think it’s out of your power to fix this problem, sorry about that I should have responded regardless :)

What I’m doing for the time being is forcing Unity to use .net framework 4.x as mentioned in my previous post (when I need to debug) hopefully that’s helpful to someone else in the future.

**Comment by van800** [comment]
Sorry, I didn't get what exactly prevents you from setting target framework = 3.5 with LangLevel = 6?

**Comment by WellFiredDevelopment** [comment]
I’m using c# 7.0 features.

**Comment by van800** [comment]
Why not target framework = 3.5 with LangLevel = 7?

**Comment by WellFiredDevelopment** [comment]
This is what I’m doing however when I do this, the issue presents itself that I cannot debug my solution with rider attached, see the following message

‘’’
Little bit of an update on this, it seems to be an issue with later versions of mono since they've been switched over to use the Roslyn compiler, which only generates pdb files.

Rider complains that : 'Old versions of mono don't support pdb files'’’’

:(

**Comment by van800** [comment]
Are you on mac or win?
There are some options on that.
For any OS you may use roslyn compiler to build and pdb2mdb to convert pdb to mdb.
For *nix OS you may try Unity mono + Unity xbuild 14.
I am very interested to make it more straightforward in Rider, though haven't time to check it more thoroughly. It will help, if you can share more details on how your solution look like.
Does manually prepared solution contain both Unity-generated projects and custom dll-projects? Or you have separate solution for dll-projects?

**Comment by WellFiredDevelopment** [comment]
Generally setup with two seperate solutions, we build either on Linux (1 developer + ci machine) and macOS. 99.9% of the code exists in a non Unity generated Solution.

I’m more than happy to provide you with a sample solution so you can see our setup, give me a day and I’ll create you a lightweight sample project and I’ll upload it here.

We mostly work outside of Unity since it provides us with a more powerful development environment, we’re primarily shipping tools to end users so the intricacies of our development environment never really leave our office.

**Comment by ArtOfSettling** [comment]
As promised, here is an update with a small example illustrating the issue.

[example.zip](https://github.com/JetBrains/resharper-unity/files/1497141/example.zip)

In the root directory you'll see two folders : 
unity - All Unity stuff
solution - Has the offending solution.

If you want to see the issue simply attach the rider with the sln found in solution directory to an instance of Unity open with the Unity Project inside the unity folder.

**Comment by van800** [comment]
Thanks much!
I am on linux, it must very similar to mac.
I see that Dll projects have LangVersion is 6 and TargetFrameworkVersion v3.5
In Rider I have mono executable path "/opt/Unity/Editor/Data/MonoBleedingEdge/bin/mono"
and MSBuild 14 "/opt/Unity/Editor/Data/MonoBleedingEdge/lib/mono/xbuild/14.0/bin/xbuild.exe"
In Unity solution I just added a cube to the Scene and attached SimpleBoostrapTest to that gameobject.
Opened "offending solution", attach to UnityEditor, enter Play mode in Unity and brakepoint was hit fine.

One thing I recognized that in unity/Assets/WellFired/WellFired.Example you have pdb-s instead of mdb-s. Could you please recheck mono and msbuild paths in your setup?
Again many thanks!

**Comment by WellFiredDevelopment** [comment]
Hello,

whilst I setup the project I must have forgot to save the solution after setting Lang level 7.0. If you set Lang level to 7.0, you’ll see that pdbs are generated, which in turn causes the debugger to not connect.

Sorry about that! I could re up a new solution but I guess you can set the Lang level to 7 locally in order to see the problem.

It is probably possible for me to use pdb2mdb if you think that’s he only way to make this work. (Other than forcing Unity to 4.6), let me know :)

**Comment by van800** [comment]
Now I see the problem, that old xbuild refuses to compile project with LangLevel = 7.
I plan come up with some pdb2mdb solution.
Thanks again!

**Comment by van800** [comment]
@WellFiredDevelopment Have you ever tried your scenario on VS for mac?
I found out that pdb2mdb will not help on *nix because pdb-s compiled there are portable pdb. Portable pdb-s are completely different format than old windows-only pdb.

**Comment by ArtOfSettling** [comment]
I tried exclusively on Mac and Linux with Rider.

**Comment by van800** [comment]
It is fine, I will check.

**Comment by van800** [comment]
I have checked VS for Mac, unfortunately it doesn't work either.
https://stackoverflow.com/questions/47894562/how-to-convert-portable-pdb-ppdb-to-mdb

**Comment by van800** [comment]
@ArtOfSettling You may check how debugging the decompiled code workarounds the problem.
https://blog.jetbrains.com/dotnet/2018/02/20/working-external-class-libraries-unity-rider/

**Comment by kivan-mih** [comment]
Hi! I got almost the same problem and for me the reason was - I started Unity from a symlink with the name "Link to Unity Editor", so it seems Rider tried to identify Unity by process name and failed with the name of symlink. When I renamed symlink to "Unity" everything started to work fine. It was very confusing at first, because Rider have shown small icons on the bottom panel, which notified that connection with Unity was established successfully, so I spent a plenty of time trying to find a solution for this problem. Maybe it will help someone. 
(Rider 2018.1, Unity 2018.2.2f1)

**Comment by van800** [comment]
@kivan-mih You are right. Here is the corresponding piece of code.
https://github.com/JetBrains/resharper-unity/blob/182/rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/attach/UnityRunUtil.kt#L14

**Comment by kivan-mih** [comment]
@van800  maybe use contains+toLowerCase instead of just startsWith?.. Also maybe inform Rider user somehow in UI that it is nescessary? it could save much time for some random people like me.

**Comment by van800** [comment]
https://github.com/JetBrains/resharper-unity/pull/713

**Comment by kivan-mih** [comment]
@van800 Thx, nice!

**Comment by citizenmatt** [comment]
Is this issue resolved? Can we close it?

**Comment by kivan-mih** [comment]
Probably yes, at least my problem seems to be covered by @van800 commit

**Comment by citizenmatt** [comment]
OK, closing for now. If there's still an issue, please comment or open a new issue.
