### ISSUE TITLE
Reference to JetBrains.Annotation get included in IL2CPP iOS output

### ISSUE THREAD

**Issue by mleenhardt** [JetBrains/resharper-unity#276]
I noticed today that when explicitly using a  `ContractAnnotationAttribute` on a method, a bunch of references to `JetBrains.Annotations.*` get included in the generated IL2CPP on iOS.

Is this expected and is there a way to remove them outside of manually post processing the files?

I'm just wrapping all R# attributes in `#if UNITY_EDITOR` but there might be a more elegant solution to deal with this.

Unity 2017.1.1p4
Rider 2017.2
Build #RD-172.4144.1459, built on October 11, 2017
JRE: 1.8.0_152-release-915-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by van800** [comment]
I guess this issue is not be related to Rider or its Unity plugin, I guess if you switch to MD it will just be the same. We do not change the way how Unity compiles code or makes IL2CPP. Please contact Unity support about it. Please follow up here if you get any new information about the issue.

BTW Some time back I noticed that JetBrains.Annotations are compiled in UnityEngine.CoreModule.dll. And reported it to Unity team.

**Comment by mleenhardt** [comment]
Oh the JetBrains attributes are actually built into the Unity dll itself, didn't realize this. I was just assuming they came from Rider which made them available to the c# project.
