### ISSUE TITLE
Intellisense not working on Unity Event Functions

### ISSUE THREAD

**Issue by archer3cl** [JetBrains/resharper-unity#282]
I'm unable to use the option Generate Code -> Unity Event Functions or auto completing Unity Event Functions (Update, Awake, OnCollision, etc)

![example](https://user-images.githubusercontent.com/4583932/32960536-cbfabb70-cb8a-11e7-86ab-ce3b1c0a9a1d.png)
![example2](https://user-images.githubusercontent.com/4583932/32960655-5d8cc34e-cb8b-11e7-932c-a18e069429c3.png)

I can, however, use the auto completion if i disable the resharper Intellisense option in Resharper -> Options -> Intellisense -> General

With Visual Studio 2017, Unity 2017.2.0f3 and this plugin 2.0

**Comment by citizenmatt** [comment]
I suspect this is a project that isn't managed by Unity - which means it's missing a Unity define, which we use to get the version of the API. You need to have a symbol such as `UNITY_5_5` defined in the .csproj, so we know what version of the API to target.

I'm not sure what to do as a reasonable alternative here. Ideally, we'd use the `ProjectVersion.txt` file, but then we'd have to find it from a non-Unity managed project. Where do you store your solution file?

**Comment by archer3cl** [comment]
How can I tell if it's being managed by Unity?

My solution file it's in the same folder as my Unity project. I don't have any special configuration. It's a starter project from Unity and then I created a script from the inspector. After that I double click on the generated file and then visual studio opened

**Comment by citizenmatt** [comment]
Hmm. That doesn't sound like the same issue. Are you able to share the .csproj files, please?

**Comment by archer3cl** [comment]
Sure


[Zkick.zip](https://github.com/JetBrains/resharper-unity/files/1483436/Zkick.zip)

**Comment by citizenmatt** [comment]
Ah, I think this is a bug in 2.0 of the plugin, which only knew about the Unity API up to version 2017.1. If you used anything newer than that, code generation would fail - see #219.

This has been fixed in 2.1 of the plugin, which you should be able to download from ReSharper's Extension Manager. It knows about the Unity API up to version 2017.3, and will also gracefully fall back to the last known version if it encounters a newer version of Unity.

I'm going to close this issue now. Please update and see if that fixes things. Feel free to reopen if it's still not working.
