### ISSUE TITLE
UnityStandardAssets can't be recognized without changing folder name

### ISSUE THREAD

**Issue by EntranceJew** [JetBrains/resharper-unity#305]
As referenced in issue #6, there doesn't appear to be a way to rename folders in a solution to match a namespace.

My main issue is that `Assets/Standard Assets/Cameras` does not line up with `UnityStandardAssets.Cameras` -- and renaming/moving folders and files downloaded from the Asset Store is very dangerous to do (it can prevent correctly redownloading the files or perhaps misidentifying similar files), although it would appear to be the only thing I could do to correct the issue.

Is there a way to arbitrarily rename this folder's namespace without renaming the folder?

**Comment by EntranceJew** [comment]
I'm also faced with this issue when using another Asset Store item: `Chart and Graph`, which it believes should be generated in the namespace `Chart_and_Graph` but its actual namespace is `ChartAndGraph`.

**Comment by citizenmatt** [comment]
Unfortunately, the ReSharper engine doesn't support this. When checking namespaces, it tries to match the full namespace with the folder structure of the project. We can skip one or more folders (e.g. ignore `Assets` in the expected namespace), but we can't a) use a different name for a folder, or b) disable the check for only certain folders and sub-folders.

This is something that should really be addressed in the ReSharper engine, rather than the Unity plugin, so I've raised an issue against ReSharper that you can comment on, vote for and track: [RSRP-182761](https://youtrack.jetbrains.com/issue/RSRP-182761).

In the meantime, it's possible to change the severity of this warning through the <kbd>Alt</kbd>+<kbd>Enter</kbd> menu, so you can drop it down to "Hint" or even "Do not show".

**Comment by EntranceJew** [comment]
I commented on the issue, but to clarify here for anyone that happens across it:
![wowie zowie](https://i.imgur.com/nMNMy5k.png)

It isn't a warning by regular means, code is straight up not found and causes all sorts of warnings to go off because of it although it's valid code.

**Comment by citizenmatt** [comment]
Oh, this is something entirely different. Rider doesn't require namespaces to match folder structure in order to find code - it uses whatever code is included in the project, and has to use whatever namespace the class is declared in.

The warning I was discussing above is simply a code style/best practice warning, to match the convention that namespaces usually (but are not required to) match the folder structure.

Is the `AbstractTargetFollower` class included in the project? Is it declared in the `UnityStandardAssets.Camera` namespace?

And more importantly, does the project compile? Both in Unity and in Rider? Unity handles compilation internally, while Rider is trying to use msbuild.

**Comment by EntranceJew** [comment]
AbstractTargetFollower is in the project, here's how it looks if it exists in a folder named `UnityStandardAssets`:

![USA! USA!](https://i.imgur.com/rzpJghV.png)
![code shows fine to me](https://i.imgur.com/nsvFcXX.png)

And here's how it looks if it exists inside `Standard Assets`:
![code shows up scared and broken](https://i.imgur.com/L7XLcKO.png)
![code doesn't show up in the Assembly-CSharp](https://i.imgur.com/13mldFW.png)

The Unity project builds just fine with it named Standard Assets or UnityStandardAssets but Rider can't build it either way because of this error: ![first pass](https://i.imgur.com/WOSYWxi.png)

It works if I re-enable the `-firstpass` for the Editor and the regular Assembly but I have no idea why certain files show up there instead of the first two projects so I generally disregard them. Sometimes CameraGuidelines.txt is in the main assembly and sometimes _sources.txt is in the firstpass. Doesn't make any sense to me. Rider also builds in either scenario if I have these enabled instead of unloaded.

I'd rather have the file view but since there's no easy way to just ignore .meta files and whatever files are in the .gitignore it's impossible to use since everything draws as yellow.

**Comment by van800** [comment]
@EntranceJew Why do you unload projects? What is the benefit?
Could you please provide us a sample demonstrating the problem?
Rider doesn't generate sln and projects, we open just what Unity generates with some minor modifications.

**Comment by citizenmatt** [comment]
You need to leave the projects loaded - unloading means Rider can't see the code that's in those projects, and this error is because of that.

The `Standard Assets` folder is treated specially by Unity, and anything in this folder, `Pro Standard Assets` or `Plugins` is compiled first, in the `Assembly-CSharp_firstpass` project. This is so that any code in `Standard Assets` is already compiled and ready for use by the main project. This is not so important for modern versions of Unity, but in the past, it was the only way to make the code in `Standard Assets` available to be called from a main project written in UnityScript.

 that the Standard Assets are compiled first, and then it would be available to your code written in UnityScript. This is less of a concern if your code is all in C#, but it's just the way Unity works. See the doc pages on [Special folder names](https://docs.unity3d.com/Manual/SpecialFolders.html) and [Special folders and script compilation order](https://docs.unity3d.com/Manual/ScriptCompileOrderFolders.html) for more details.

Unity will include .txt files in all projects. It's a little annoying, but that's just the Unity way.

We do plan on having an Asset view at some point in the future, which would show a view of the project in much the same way that Unity currently displays Assets and the project structure.

**Comment by van800** [comment]
Please feel free to reopen, if the problems is still actual.
