### ISSUE TITLE
Rename Methods in Scene Files

### ISSUE THREAD

**Issue by tinjaw** [JetBrains/resharper-unity#32]
When you have things like events tied to button clicks, they are embedded in the .unity (scene) file as strings. (see m_MethodName: in a text (not binary) scene file).

When Resharper suggests changing the method name in the .cs file, it should take into account any matches in scene files. If the method name is changed, R# should also change it in the scene file to keep them linked.

**Comment by citizenmatt** [comment]
I don't know Unity well enough here. Do you have a sample that can show the `.unity` file in use?

**Comment by tinjaw** [comment]
I think all you need to worry about is

m_MethodName: OnClick

Where OnClick is the string that gets changed if the method is renamed by
ReSharper.

Attached are two files. One with no action attached to the button click and
one with the action added, so you can see everything associated with adding
an action method.

Please let me know if you need more information.

PS. A .unity file is a Scene File. You would need to grep every .unity file
and look for the method.

**Comment by TarasOsiris** [comment]
Not really a good idea as half of the times scenes are serialized to binary and you won't be able to modify it.

**Comment by citizenmatt** [comment]
This could be an interesting extension. It would require teaching ReSharper a new file format, which is a non-trivial task (but could be fun :smile:), and it does look as though it would require Unity to only save in text format, rather than the default binary. It also looks like the `.unity` files aren't added to the `.csproj` files by default, and ReSharper doesn't really know about files that aren't part of the project.

I'm trying to clean up the issues list, so I've moved this to a "Someday" milestone, as something to think about for a later time.

**Comment by cmcpasserby** [comment]
due to the possibility of hosing a whole scene doing this, the best use of it i could see, would be having resharper let you know what scenes and prefabs your Component is referenced in.

**Comment by Temka193** [comment]
it really would be useful

**Comment by andgeno** [comment]
Would also like to have this feature. It's really tedious to re-map those broken links every single time after refactoring a method's name.

**Comment by StephenHodgson** [comment]
Fryi, Serialization doesn't just happen for scene assets, but any serialized asset like a prefab, scriptable object, or even inspector.

**Comment by citizenmatt** [comment]
Fixed in #1140
