### ISSUE TITLE
private field with SerializeField attribute in non-monobehaviour classes produce "never assigned" warning

### ISSUE THREAD

**Issue by XtroTheArctic** [JetBrains/resharper-unity#324]
Hello. Not 100% sure but probably, I started to experience this problem in last update.

It was working fine before the update. Resharper Unity plugin was filtering out those warnings even on non-monobehaviour classes.

I have my own serialization logic for non-monobehaviour classes and I want those warnings to be filtered out because I declare the SerializeField attribute like it was before.

Please see the screenshot.

Can you please confirm and fix this?

![adsiz](https://user-images.githubusercontent.com/6631429/34623434-5ef4a9e4-f21f-11e7-815f-3318a9a8a280.png)

**Comment by citizenmatt** [comment]
Yes, this behaviour changed in the last update, to more accurately reflect what happens.

Previously, anything with a `[SerializeField]` attribute was marked as implicitly assigned by Unity, even if the class had nothing to do with Unity. Now fields are only marked as a) serialised and b) implicitly assigned if Unity will actually do it. This (usually) makes the "never assigned" warnings more accurate, as these fields will be unassigned because Unity won't be doing it.

However, if you have your own custom serialisation logic, then you will see these "never assigned" warnings. The easiest way to fix this is to apply an annotation attribute. You can add the `[UsedImplicitly(ImplicitUseKindFlags.Assign)]` attribute (it's a JetBrains attribute, but it's embedded in UnityEngine.dll, so you're fine to use it) to the field. This tells ReSharper that the field is being used implicitly (i.e. not explicitly in code in the project) and that when it is, it's being assigned. This is effectively the same annotation that the plugin is applying via code.

Alternatively, if it's the `[AutoLink]` attribute that is marking this field as being serialisable, then you can mark the `[AutoLink]` attribute itself with the `[MeansImplicitUse(ImplicitUseKindFlags.Assign)]`, which tells ReSharper that whenever it sees the `[AutoLink]` attribute being used, it means that the target (the field) has a value that is implicitly assigned.

**Comment by XtroTheArctic** [comment]
One of the best answers on Internet!! Thank you.

I applied it to my AutoLink attribute and it helped me to clean a huge amount of "#pragma warning disable 649" lines in my code base.
