### ISSUE TITLE
Live templates for C#

### ISSUE THREAD

**Issue by bit-chimp** [JetBrains/resharper-unity#354]
Ability to auto import/shorten namespaces

**Comment by van800** [comment]
Could you please provide more details?
What are steps to reproduce, expected and actual results, please.

**Comment by bit-chimp** [comment]
This is actually meant to be a suggestion rather than an issue. I was wondering if it would be possible to implement auto namespace generation + auto importing other classes?
````
$namespace$ (generate this class' namespace)
public class $class_name$ : Entitas.IComponent (shorten this by importing Entitas package)
{
}
````

**Comment by citizenmatt** [comment]
This is already supported. When you create a Live Template, you can create a variable, just like `$namespace$`, and assign them a macro, such as "basic completion" or "default namespace". And there's also a checkbox to shorten references, which will automatically add any `using` statements required to shorten a fully qualified name. More details are available in this [overview](https://www.jetbrains.com/resharper/features/code_templates.html), and in the [documentation](https://www.jetbrains.com/help/resharper/Creating_a_Live_Template.html).

You can see this in action in the [MonoBehaviour template](https://github.com/JetBrains/resharper-unity/blob/master/resharper/src/resharper-unity/Templates/MonoBehaviour.md) (it's in this repo as a markdown file, but as part of the build process gets "compiled" into the correct XML based format).

The only downside is that we can currently only edit templates in ReSharper - we haven't yet ported over and integrated the editing of Live Templates into Rider (although if you have both ReSharper and Rider installed on the same machine, the edits in ReSharper are visible in Rider, too). This issue is tracked here: [RIDER-548](https://youtrack.jetbrains.com/issue/RIDER-548).
