### ISSUE TITLE
API parser should handle obsolete banners in docs

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#411]
using UnityEditor;

namespace JetBrains.Rider.Unity.Editor.AssetPostprocessors
{
  public class ModificationPostProcessor : UnityEditor.AssetModificationProcessor
  {
    public const string ModifiedSource = "com.jetbrains.rider.modifiedsourcefile";
    
    private static void OnWillCreateAsset(string path)
    {
      var isCs = path.EndsWith(".cs.meta");
      if (isCs)
        EditorPrefs.SetBool(ModifiedSource, true);
    }

    private static AssetDeleteResult OnWillDeleteAsset(string assetPath, RemoveAssetOptions options)
    {
      var isCs = assetPath.EndsWith(".cs.meta") || assetPath.EndsWith(".cs");

      if (isCs)
        EditorPrefs.SetBool(ModifiedSource, true);

      return AssetDeleteResult.DidNotDelete;
    }

    private static AssetMoveResult OnWillMoveAsset(string fromPath, string toPath)
    {
      var isCs = fromPath.EndsWith(".cs");

      if (isCs)
        EditorPrefs.SetBool(ModifiedSource, true);

      return AssetMoveResult.DidNotMove;
    }
  }
}

**Comment by citizenmatt** [comment]
This is for the EditorPlugin project, right? If so, then it's not showing up because that project doesn't have a Unity version associated with it, so we default to the oldest we support, which is 5.0. And `UnityEditor.AssetModificationProcessor` was introduced in 5.1.

If you set a Unity version for the project of 5.1 or above, it will pick it up. We look at defines for this, so set `UNITY_5_5` or `UNITY_2018_1` or something like that.

**Comment by van800** [comment]
Yes, it is for EditorPlugin.
But documentation here seems to be not correct.
See Editor from Unity 4.7

![image](https://user-images.githubusercontent.com/1482681/36935261-f6d4c016-1ef5-11e8-86b7-a606023ae421.png)

**Comment by citizenmatt** [comment]
Ah. Looks like an issue with the parser - I think it's getting confused about [the "obsolete" banner with the 5.0 version of the docs](https://docs.unity3d.com/500/Documentation/ScriptReference/AssetModificationProcessor.html). I'll change the title of the issue and add it to the 2018.1 milestone.
