### ISSUE TITLE
Never suggest to make fields readonly if they are marked with SerializeField

### ISSUE THREAD

**Issue by SugoiDev** [JetBrains/resharper-unity#419]
Unity doesn't like readonly fields in serialization, so when a field is marked with the `SerializeFieldAttribute`, the suggestion to "Field can be made readonly" should be suppressed, since it will cause that field to silently no longer be serialized by Unity.

Related issues #291 and #25 

![screenshot 2018 03 07-03 03 15](https://user-images.githubusercontent.com/7355630/37076478-8f6c238e-21b5-11e8-9889-4b537f31d1f4.png)

**Comment by citizenmatt** [comment]
This only happens in classes that are not Unity based, e.g. not derived from `MonoBehaviour`. This is because we don't mark any fields, even those with attributes, as implicitly used unless they are in a Unity class.

Behaviour should be:

* If the custom class has a `[Serializable]` attribute, handle all fields as though they're on a `MonoBehaviour`. I.e. public fields or those marked with `[SerializeField]` are implicitly used, `[NotSerialized]` disables this. Highlight the fields as Unity fields (gutter icon)
* If a class does not have the `[Serializable]` attribute, highlight usages of `[SerializeField]`. I think it should be a redundant highlight - the attribute does nothing, so grey it out. Quick fix to remove, another to add `[Serializable]` to the class. (Alternatives would be hint or suggestion on the attribute to require `[Serializable]` on the class, as this is clearly the intention)

**Comment by julia-vaseva** [comment]
Cross-link https://youtrack.jetbrains.com/issue/RIDER-12239

**Comment by citizenmatt** [comment]
see also [RIDER-9341](https://youtrack.jetbrains.com/issue/RIDER-9341)

**Comment by 3darkman** [comment]
as shown in the image, this error has returned.

![image](https://user-images.githubusercontent.com/20743586/90138170-f7a10780-dd4c-11ea-9891-751064cf287d.png)

**Comment by fuj1n** [comment]
Getting this in Rider 2023.2 with JetBrains Rider Editor 3.0.24

Seems like inherited Serializable attributes aren't considered in the above-mentioned fix.

![image](https://github.com/JetBrains/resharper-unity/assets/4004193/f0d29b2c-600c-4355-8e1a-e4e9a124f953)
