### ISSUE TITLE
Feature Request: Support for IEnumerator Start()

### ISSUE THREAD

**Issue by Silentor** [JetBrains/resharper-unity#52]
Sometimes it can be handy to use Start() callback as a Coroutine, see:
http://answers.unity3d.com/questions/754968/can-monobehaviorstart-return-an-ienumerator-hint-y.html
Resharper-unity supports `void Start()`, but not `IEnumerator Start()` for now. There are some other default Monobehavior callbacks with same feature, but docs a lack of info.

**Comment by citizenmatt** [comment]
So, I reckon the following changes:

- Messages that can be coroutines should be marked as in use if the return type is `void` or `IEnumerable`
- Generating messages via auto-popup as you type should create a live templates hotspot on the return type, listing `void` and `IEnumerable`. Selecting one will then position the caret inside the method.
- Generating messages via the Generate action should be able to create co-routines. Options for implementation:
  - Perhaps add two menu items to the Generate menu - "Generate Unity messages" and "Generate Unity co-routines"
  - Perhaps add a second page to the Generate dialog. First page lists available messages, second page allows choosing which ones of the selected are treated as co-routines
  - I _think_ it might be possible to add extra controls into the Generate dialog list. Could combine selecting message and setting the type of message
- Figure out which messages can be co-routines

Does that cover the functionality required?

The trickiest thing I can see is getting the list of messages that can be co-routines. This can be in the docs "Awake cannot be a co-routine", or "OnApplicationFocus can be a co-routine; to do this, use the yield…", but equally might not be mentioned. It looks like the text is just free form. So, questions:

* How do we identify co-routines?
* Can we make this part of the automatic doc parsing that gives us all messages?
* What's the default if the message doesn't have a co-routine?

**Comment by Silentor** [comment]
> How do we identify co-routines?

As you mention, coroutine messages described free form in docs :( And I dont know any way to extract possible message coroutines by decompiling Unity managed dll's. So I prepare a list of messages that can be Coroutines for sure (directly mentioned in docs, except for Start):

- Start (not directly mentioned in docs but has several Unity examples and my own experience) https://docs.unity3d.com/ScriptReference/WaitForEndOfFrame.html https://docs.unity3d.com/ScriptReference/MonoBehaviour.StartCoroutine.html

- https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnPostRender.html
- https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnPreRender.html
- https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnTriggerEnter.html
- https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnTriggerExit.html
- https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnTriggerStay.html
- https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnMouseDown.html
- https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnMouseDrag.html
- https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnMouseEnter.html
- https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnMouseExit.html
- https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnMouseOver.html
- https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnMouseUp.html
- https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnMouseUpAsButton.html
- https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnParticleCollision.html
- https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnApplicationFocus.html
- https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnApplicationPause.html
- https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnBecameInvisible.html
- https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnBecameVisible.html
- https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnCollisionEnter.html
- https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnCollisionExit.html
- https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnCollisionStay.html

My personal wish - is just mark Coroutine messages as in use, because Coroutine messages is an advanced rarely used feature. But live template generation can be useful.

**Comment by jizc** [comment]
@citizenmatt I just want to point out that it is indeed `IEnumerator` like @Silentor wrote in the first post, not `IEnumerable`.

**Comment by citizenmatt** [comment]
OK, it works a little differently to originally planned. Event function methods are generated just as they were previously - no coroutine support. The biggest issue is that it's really hard to fit neatly into the UI. For example, the generate dialog allows creating multiple methods at once, but maybe only some should be coroutines, and there's no easy way of specifying which ones. And since coroutines are an advanced feature, it's easier to create standard event functions and then provide tooling to convert them after.

So, there are now context actions (and tooltips) on methods that support being a coroutine that will convert to/from coroutine, and update the return type appropriately. The usage inspector now also understands coroutines and will mark them as in-use.

Furthermore, there are now inspections and quick fixes on event function signatures - return type, `static` modifier and parameters. If they are wrong, they will be marked as a warning and Alt+Enter will quickly fix them up. A method will only be marked in-use if it's an exact match, signature and everything. But if there's only partial matches (name), these methods will still be marked with the gutter icons, and warnings to fix up signatures.
