### ISSUE TITLE
Add doc xml to Unity libs package 

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#543]
UnityClassLib:
![image](https://user-images.githubusercontent.com/1482681/39350026-3ee960f0-49fd-11e8-8de0-50e3c414a682.png)

Unity-generated project
![image](https://user-images.githubusercontent.com/1482681/39350087-6758b518-49fd-11e8-91b1-808833542e97.png)

**Comment by citizenmatt** [comment]
This is because there isn't a `UnityEditor.xml` file in the same directory as the referenced `UnityEditor.dll` - the EditorPlugin project is referencing Unity libs via a private nuget package, and that package doesn't include the xml file.

Incidentally, that package has very confusing versioning - the package name is 2017.3.0f3, but it's version is 2018.3.5?

**Comment by van800** [comment]
Thanks for clarification, I will update the package.
