### ISSUE TITLE
Plugin no longer works after upgrading to Resharper 2018.1.2

### ISSUE THREAD

**Issue by rob8861** [JetBrains/resharper-unity#584]
After upgrading to Resharper 2018.1.2, the Unity plugin stopped working correctly.
When I try to type MonoBehavior functions, the intellisense window pops up but the autocomplete and snippet insertion no longer work. I keep getting an error message "Cannot resolve symbol <MonoBehavior method name>"

**Comment by rob8861** [comment]
EDIT: tried to downgrade resharper, same problem.
tried different versions of Unity, same problem
tried reinstalling plugin, same problem.

I am not sure what happened, but it started after upgrading to Resharper 2018.1.2.

**Comment by rob8861** [comment]
EDIT: 
I was able to "resolve" this issue by downgrading all the way back to 2018.1
Apparently that was the version I had prior to upgrading to 2018.1.2
so I know that the plugin is broken in the following versions:
2018.1.1 and 2018.1.2

When can we expect an ETA for a fix and why do Resharper users don't get frequent updates like Rider users.

**Comment by citizenmatt** [comment]
Hmm, the plugin from 2018.1 should be compatible with 2018.1.1 and 2018.1.2, I'll take a look to see if something's changed when it shouldn't.

As for updates, Rider doesn't _really_ get more frequent updates than the ReSharper plugin. We release a new version for each new version of ReSharper, such as 2017.3 and 2018.1. 

However, because Rider bundles this plugin, early updates are available in the form of Rider EAP builds, while ReSharper only gets a release for the RTM version. Rider has also seen updates in 2018.1.1 and 2018.1.2, but these updates have only been related to the integration with the Unity editor, which doesn't affect the ReSharper plugin, which doesn't have this integration.

**Comment by rob8861** [comment]
@citizenmatt Thank you for the reply and taking the time to look at this weird issue. 
I can confirm that I was able to reproduce this issue on 3 different computers with similar environments (Win10, VS2017 and Resharper > 2018.1)

I've been following the Resharper performance blog and the team is working hard on improving R# many known performance issues.  I'd love to be able to upgrade back to 2018.1.2 when this issue is resolved.

Thanks,

**Comment by oxysoft** [comment]
Same deal here.

**Comment by citizenmatt** [comment]
Just a quick update - this is due to a breaking change in an API in ReSharper 2018.1.2. We try not to have API changes in maintenance releases, but unfortunately, we didn't catch this one. It's an awkward one to work around so that we remain compatible with 2018.1 RTM and 2018.1.2, but I'm hoping I can get a release out later today.

**Comment by rob8861** [comment]
@citizenmatt shouldn't this also affect Rider users since they both share the same Resharper code base?
Also, why would the Resharper team make a breaking changes to an API in a minor release. And if those changes are absolutely necessary, shouldn't the old API should at least be marked as deprecated to give plugin developers enough time to make the necessary changes. 

Thanks again for fixing this issue.

**Comment by citizenmatt** [comment]
It doesn't affect Rider because the Unity plugin is bundled, and we have an internal TeamCity build that recompiles the plugin based on latest commits to the R#/Rider/dotnet repo (this also explains the weird branch names - we mirror the main repo's branches). The breaking change was source compatible - it added some default parameters to a method, so recompiling didn't show any breaks. But default parameters are embedded in the caller, not the method declaration, so we end up an existing caller looking for a method with a signature that no longer exists.

The tricky thing now is that if I recompile with the new SDK, it'll work on 2018.1.2, but fail in 2018.1 RTM, and vice versa. So I'm having fun with compiled expression trees instead :)

And we do indeed check for breaking API changes in maintenance releases - all commits for the maintenance releases are cherry picked from master, and peer reviewed for minimal impact. But it's a manual process and this one just slipped through.

**Comment by citizenmatt** [comment]
I've just pushed the updated version to the ReSharper gallery. If you go to ReSharper -> Extension Manager, you should see a new version ([2018.1.0.380](https://resharper-plugins.jetbrains.com/packages/JetBrains.Unity/2018.1.0.380)). Update and restart and it should all be working again. Please reopen if there are still issues.

Apologies for the inconvenience.
