### ISSUE TITLE
Disable naming rules for Unity methods like OnGeneratedCSProjectFiles

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#72]
Now Rider wants to rename this to OnGeneratedCsProjectFiles

**Comment by citizenmatt** [comment]
This should already be implemented. But I think this is another bug I've just found - `OnGeneratedCSProjectFiles` should be static. I suspect it's been generated as an instance method. Add `static`, and I bet it works.

Although, this might be because Rider is using an older version of the plugin, without these undocumented messages, in which case, this is just #59. I need to update and push a new version.

**Comment by citizenmatt** [comment]
See #73

**Comment by van800** [comment]
it is static in my code, so I will wait for plugin update. Thanks!
