### ISSUE TITLE
Using a dynamic requires Microsoft.CSharp.dll

### ISSUE THREAD

**Issue by PandawanFr** [JetBrains/resharper-unity#721]
When I use the (.Net 4.6) `dynamic` type and try to use the `Equals` method using that dynamic object, ReSharper gives me the error _"One or more types required to compile a dynamic expression cannot be found. Are you missing references to Microsoft.CSharp.dll and System.Core.dll?"_

The only way to fix it was to add Microsoft.CSharp.dll to references.

I am guessing this is ReSharper thinking that Microsoft.CSharp.dll isn't included while it probably has a different name/equivalent in Unity (which is why it doesn't return that error inside Unity). So I'm thinking that maybe `resharper-unity` could add support for dynamics in some way so that it doesn't do that error. 

Here's a picture of the error itself. (In this example, `GetValue()` returns a dynamic type).
![Imgur](https://i.imgur.com/ZE9e3Qh.png)

**Comment by SugoiDev** [comment]
Got that too quite a while ago, and ended up just dropping a copy of Microsoft.CSharp.dll on my project.
I only use it on the editor, so I don't know if it has any side effect in a build (or if it works at all).

**Comment by PandawanFr** [comment]
Yeah, that's what I ended up doing as well. But I'm worried that it might have effects on the build in some way. Also, it'd be nice not to export "useless" packages.

**Comment by van800** [comment]
Please try mcs.rsp as suggested here and let me know the results.
https://youtrack.jetbrains.com/issue/RIDER-17277#focus=streamItem-27-3001597-0-0

**Comment by SugoiDev** [comment]
This workaround doesn't work with the new Incremental Compiler.
Creating a csc.rsp with the reference to Microsoft.CSharp will show the warning below:

---

C:\Users\User\AppData\Local\Unity\cache\packages\staging-packages.unity.com\com.unity.incrementalcompiler@0.0.42-preview.19\.bin\Microsoft.CSharp.dll(0,0): warning MSB3245: Could not resolve this reference. Could not locate the assembly "C:\Users\User\AppData\Local\Unity\cache\packages\staging-packages.unity.com\com.unity.incrementalcompiler@0.0.42-preview.19\.bin\Microsoft.CSharp.dll". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.

**Comment by van800** [comment]
@SugoiDev I believe it is a Unity issue.
@citizenmatt how do you think should we implement a workaround or accept a PR on this?
It can be done the same way as we add references from mcs.rsp,. https://github.com/JetBrains/resharper-unity/blob/182/unity/EditorPlugin/AssetPostprocessors/CsprojAssetPostprocessor.cs#L349

**Comment by SugoiDev** [comment]
Yeah. The incremental compiler is just a modified Roslyn compiler, so it doesn't have that library (since the Microsoft.Net.Compilers package doesn't). The issue happens because Unity didn't modify it find references added by a response file in mono's libraries.

**Comment by citizenmatt** [comment]
OK, so as I understand it:

* Unity works just fine with `dynamic` - it compiles and runs games, etc.
* Rider doesn't recognise it because the generated .csproj files don't include a reference to `Microsoft.CSharp.dll`
* Adding a `csc.rsp` (or other flavour of response file) can work because Rider will add those references to the `.csproj` when they're generated.

If all this is true, then I think we should add a reference to `Microsoft.CSharp.dll` in `.csproj` generation. If Unity works fine, and we don't, we need to fix up the project file so that we do. Adding a response file is a workaround to make Rider work, not to make Unity work.

**Comment by SugoiDev** [comment]
With the Incremental Compiler, Unity does not work properly with "dynamic" without actually a copy of the DLL in the Assets folder (won't compile). Rider does not mind the "dynamic" keyword in this case.

I'm not sure if it would be any different with the legacy compilers.

**Comment by citizenmatt** [comment]
The legacy compiler finds `Microsoft.CSharp.dll` with no extra help - it creates its own (internal, temporary) response file that includes `-lib:…` option to point to the correct Mono folder, so the implicit reference to `Microsoft.CSharp.dll` is automatically resolved.

Sadly, the incremental compiler doesn't add this, and I can't seem to make it support `-lib:…` at all. You can make it work by adding a fully qualified path to `Microsoft.CSharp.dll` inside a `-r:…`. But this is a Unity issue and isn't something Rider should try to fix.

What Rider can do is add a reference to `Microsoft.CSharp.dll` to the `.csproj` file. This fixes red code in Rider for both compilers, and because Rider does a standard msbuild compilation, we also get a clean compile, even if Unity itself will fail. We also shouldn't need to set the hint path, because the file lives in the standard target framework folder.

**Comment by van800** [comment]
There is at least one case when we shouldn't silently add Microsoft.CSharp.dll to the .csproj file. 
With Api Compatibility Level `.NET Standard 2.0` in Unity 2018.2 I am seeing 
`Dynamic operation cannot be compiled without `Microsoft.CSharp.dll' assembly reference`

**Comment by citizenmatt** [comment]
Yeah, this should be 4.x only.

**Comment by van800** [comment]
If non-Unity msbuild is used - setting hintpath will help to resolve assembly from Unity installation.
