### ISSUE TITLE
XCode dll reference is not added

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#855]
Need to check current behavior and fix if it is causing the problem.

https://github.com/JetBrains/resharper-unity/pull/843#issuecomment-431473404

**Comment by Ethan-VisualVocal** [comment]
Update: After doing a "clean rebuild" (The aforementioned: delete all Unity auto-generated files (including .csproj and .sln files), then reopen Unity and then reopen Rider 2018.3 EAP) it eventually degraded to not including the Xcode dlls again, so it's back to the behavior I regularly experience in Rider 2018.2.

Possibly due to Unity modifying the the .csproj files again and this resharper-unity plugin not re-adjusting them? 

As to why this issue came around, I'm not sure -- Rider 2018.2 DID include the correct Xcode dll files for the longest time when working with Unity 2017.4.xx versions, but a resharper-unity plugin about a month back regressed to not including all of the Xcode dll references.  

Let me know if you need more info!

**Comment by van800** [comment]
Please share correct reference to dll, which you have.

**Comment by Ethan-VisualVocal** [comment]
> > Is it true that calling Asset->Sync C# Project fixes the path to dll?
> 
> No, it just forces Unity to rewrite the .csproj files out, but the issue remains. I'll see if I can create a minimal repro project to narrow down a clean repro.

@van800 
Update: It looks to be purely a Unity bug. This only occurs in .csproj files created by asmdefs that contain files with dependencies on `UnityEditor.iOS.Xcode`

For the default csproj, everything works fine, and the reference being added is
```
<Reference Include="UnityEditor.iOS.Extensions.Xcode">
      <HintPath>/Applications/2017.4.13f1/PlaybackEngines/iOSSupport/UnityEditor.iOS.Extensions.Xcode.dll</HintPath>
</Reference>
```

For the other files, if I use Rider to manually re-add the reference (by pressing _Alt-Enter_ on an error statement, then select "Reference `UnityEditor.iOS.Extensions.Xcode` and use..." for the DLL), hit Save All in Rider, Unity then immediately re-processes and re-writes the csproj back out without the reference.

Here's the reference being added by Rider with _Alt-Enter_:
```
<Reference Include="UnityEditor.iOS.Extensions.Xcode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null">
      <HintPath>..\..\..\..\Applications\2017.4.13f1\PlaybackEngines\iOSSupport\UnityEditor.iOS.Extensions.Xcode.dll</HintPath>
</Reference>
```

Attached minimal sample: 
[XcodeDllRiderBug.zip](https://github.com/JetBrains/resharper-unity/files/2502980/XcodeDllRiderBug.zip)

**Comment by Ethan-VisualVocal** [comment]
Other clarifications: 

- Rider never seems to add the `UnityEditor.iOS.Extensions.Xcode` for asmdef created csproj files, so my original report of it is wrong, corrected in quote below: 

    - > ~However, if I close down Unity the new Resharper-Unity v2018.3.0.26 plugin gets installed, and delete all Unity auto-generated files (including .csproj and .sln files), then reopen Unity and then reopen Rider 2018.3 EAP, it DOES correctly reference the Xcode dlls.~ 
This is untrue, due to an error on my part: I failed to switch to the iOS target after this clean-rebuild, and so I simply saw no errors in Rider for the PC-target and assumed that meant the Xcode dll got added. 

- Unity itself does not report any build errors, and works fine. This is simply an error being reported by Rider's Solution-Wide Analysis. 

- After deleting the Rider plugin, switching to MonoDevelop, and forcing Unity to re-create csproj files -- Unity still doesn't produce a csproj file for the asmdef that references the Xcode dll, so the Rider plugin is _NOT harming_ anything, it's just not fixing Unity's mistakes.

**Comment by van800** [comment]
Have you considered contributing your case to the plugin code? Specifically https://github.com/JetBrains/resharper-unity/blob/183/unity/EditorPlugin/AssetPostprocessors/CsprojAssetPostprocessor.cs#L338
We will be greatful to accept PR or just code which worked for you.
Otherwise I will try to reproduce and fix.

**Comment by Ethan-VisualVocal** [comment]
@van800 I'll see what I can do over the next few evenings, so hold off on spending more time on it for now. Thanks for the starting point!

**Comment by van800** [comment]
I can't reproduce this, please comment if it is still actual, mention the path to dll on your machine. Thanks!

**Comment by cactus171** [comment]
hi.

In my case, it will be an error only in the Asset / Plugins directory.
The path of dll is "/ Applications / Unity / PlaybackEngines / iOSSupport"

Unity 5.6.p4

JetBrains Rider 2018.2.3
Build # RD-182.4231.496, built on September 13, 2018
macOS 10.13.6

Thank you

**Comment by cactus171** [comment]
I solved it Thank you
https://github.com/JetBrains/resharper-unity/commit/48327e240aac0707d49ac15e6dd118897d356d84#diff-49a0bdc810375ba0c66501b29b39a77f

I hope that if you can include it in 2018.2

**Comment by van800** [comment]
@cactus171 I will try to see what I can do.
You may use mcs.rsp with -r:"full_path_to_dll" as a workaround.

**Comment by van800** [comment]
It seems that your path is already used in Rider 2018.3 EAPs/Nightly builds. You may use JetBrains Toolbox App to manage multiple installations at once. Please follow up here.
