### ISSUE TITLE
Unity serialized field naming rule makes it impossible to vary by visibility.

### ISSUE THREAD

**Issue by Lattyware** [JetBrains/resharper-unity#859]
[As noted by englerj](https://github.com/JetBrains/resharper-unity/pull/768#issuecomment-427925303), this change has created a ton of incorrect warnings in my project that can't be turned off without turning off all inconsistent naming warnings.

A fix for this would either be to an option that allowed no special naming and to fall back to normal rules, or different naming schemes for public and private unity serialized fields.

**Comment by citizenmatt** [comment]
This really requires [RIDER-8339](https://youtrack.jetbrains.com/issue/RIDER-8339) to be implemented

**Comment by Evolht** [comment]
Sorry if this is the wrong place to put this. Is there no way to make public/private serialized fields use different naming conventions now? If I disable the unity serialized field naming, it just ignores all public/private fields naming, instead of falling back to normal naming conventions.

**Comment by citizenmatt** [comment]
There is an example in [this comment](https://github.com/JetBrains/resharper-unity/pull/768#issuecomment-432999046) that provides a manual override to allow different naming conventions for public/private. The linked RIDER-8339 issue is the correct fix for this to be part of the UI.

Out of interest, would you mind explaining your use case, please? Why do you want to have a mix of public/private serialised fields?

**Comment by Evolht** [comment]
I would only really use a public field for simple data container types. It’s more wanting to differentiate between private and public regardless of being a serialized field. It might just be me misunderstanding or using bad coding practices though. 

Thanks for your help!

**Comment by phobos2077** [comment]
IMO, using the same convention for both private AND public fields - IS a bad practice, and Rider decided to encourage this for some weird reason. I never saw any Unity code that would use some kind of special style for serialized fields, while having no difference between public & private - this just doesn't make sense.

**Comment by PixelComrades** [comment]
This still hasn't been fixed? I'm on the latest Rider and it's still doing this and there's no option to disable.

**Comment by citizenmatt** [comment]
Unfortunately, this isn't fixed. It requires [RIDER-8339](https://youtrack.jetbrains.com/issue/RIDER-8339) to be implemented, as a core part of Rider, rather than something that can be fixed from the plugin.

Just to clarify, though, it's currently possible to set up different naming standards for:

* Non-private fields (public, protected, etc.) - default is `UpperCamelCase`
* Private instance fields - default is `_lowerCamelCase`
* Private static fields - default is `_lowerCamelCase`
* Non-private constant fields - default is `UpperCamelCase`
* Private constant fields - default is `UpperCamelCase`
* Non-private static readonly fields - default is `UpperCamelCase`
* Private static readonly fields - default is `UpperCamelCase`

On top of that, there is a naming standard for "Unity serialised fields", with a default of `lowerCamelCase`. This will apply to public fields inside a Unity specific type, or to private fields marked with `[SerializeField]`. This is a more specific rule than "public" or "private" fields, and will take precedence.

Which means:

```csharp
public class MyBehaviour : MonoBehaviour
{
  public string serialisedString1;   // Unity serialised field (default lowerCamelCase)
  [SerializedField] private string serialisedString2; // Unity serialised field (default lowerCamelCase)
  private string _nonSerialisedString;  // Private instance field (default _lowerCamelCase)
}

public class DataClass
{
  public string NonSerialisedString1;  // Non-private field (default UpperCamelCase)
  private string _nonSerialisedString2;  // Private instance field (default _lowerCamelCase)
}
```

So public and private non-serialised fields have different naming standards. There is another naming standard for serialised fields, but this only applies to types that are implicitly (`public`) or explicitly (`[SerializeField] private …`) serialised fields. 

The inspection for "Unity serialised fields" can be disabled in _Preferences | Languages & Frameworks | Unity Engine_, but this prevents showing a warning, rather than treating these fields as non-serialised fields.

There is a [manual workaround](https://github.com/JetBrains/resharper-unity/pull/768#issuecomment-432999046) that adds a new rule for _private_ "Unity serialised fields" to the `.sln.dotSettings` file that is checked into source control. This is what RIDER-8339 will do - update the UI in _Preferences | Editor | Code Style | C#_ to allow building custom rules based on entity ("Unity serialised field") and visibility (public, private or any combination).

As an aside, I'm still unsure why you would have some serialised fields public and some private?

**Comment by PixelComrades** [comment]
If a class is a small [Serializable] container class then I usually make its fields public (UpperCamelCase). I think that fits the intention of that sort of class better than hiding them behind properties. In my current project I have quite a few of those. Otherwise MonoBehaviours being more complex rarely have public fields and anything that needs to be adjusted in the inspector is a private field ( _lowerCamelCase) marked [SerializeField].

I tried adding those 2 lines from the thread to the .sln.DotSettings file in the root of my Unity project directory and it did not stop the naming suggestions on public fields in a serialized class. Is there something else I'm supposed to do? I just started using Rider so I'm not that familiar with it.

**Comment by citizenmatt** [comment]
Thanks for the explanation. Interesting that it's a split on `[Serializable]`/`MonoBehaviour`.

Adding those two lines should work. I've just tested it and it seems to work ok. I've made some tweaks, so try adding this to your `.sln.DotSettings` file. You should be able to edit the file, save it and go back to Rider. Rider will read the file, update settings and should show it immediately - this is what I'm seeing when testing with Rider 2019.2.2.

The file format is horrible, in the way that only a computer can love, but it needs to be valid XML, so make sure these lines go before the closing `</wpf:ResourceDictionary>` (this is quite often added to the end of a line, rather than having its own line, so it's easy to miss. And the parser is silently forgiving):

```xml
<s:String x:Key="/Default/CodeStyle/Naming/CSharpNaming/UserRules/=e66e0435_002Dde09_002D4fdf_002Da4ba_002D16a598a0c336/@EntryIndexedValue">&lt;Policy&gt;&lt;Descriptor Staticness="Instance" AccessRightKinds="Public" Description="Unity serialized field (Public)"&gt;&lt;ElementKinds&gt;&lt;Kind Name="UNITY_SERIALISED_FIELD" /&gt;&lt;/ElementKinds&gt;&lt;/Descriptor&gt;&lt;Policy Inspect="True" Prefix="" Suffix="" Style="AaBb" /&gt;&lt;/Policy&gt;</s:String>
<s:String x:Key="/Default/CodeStyle/Naming/CSharpNaming/UserRules/=110218a1_002Dc4d4_002D4137_002Db798_002D981bc635cddc/@EntryIndexedValue">&lt;Policy&gt;&lt;Descriptor Staticness="Instance" AccessRightKinds="Private, Protected, ProtectedInternal" Description="Unity serialized field (Non-public)"&gt;&lt;ElementKinds&gt;&lt;Kind Name="UNITY_SERIALISED_FIELD" /&gt;&lt;/ElementKinds&gt;&lt;/Descriptor&gt;&lt;Policy Inspect="True" Prefix="_" Suffix="" Style="aaBb" /&gt;&lt;/Policy&gt;</s:String>
```

This adds two new custom rules - "Unity serialised field (Public)" and "Unity serialised field (Non-public)", set up to be `AaBb` and `_aaBb` respectively. You won't be able to edit either of these rules (that's what RIDER-8339 is all about), not even in the Unity settings page - that rule has a different GUID.

**Comment by vcabourdin** [comment]
I know this thread is quite old but I search a bit for this and I just saw that you can just configure this in the unity plugin configuration:
Languages & frameworks > Unity Engine > Serialized field naming rules >  
Prefix = _
Suffix = 
Style = lowerCamelCase

**Comment by gabrieldechichi** [comment]
> I know this thread is quite old but I search a bit for this and I just saw that you can just configure this in the unity plugin configuration:
> Languages & frameworks > Unity Engine > Serialized field naming rules >
> Prefix = _
> Suffix =
> Style = lowerCamelCase

This does not actually solve the problem, as it will try to force you to use the same naming convention for **any** serialized field (public or private with [SerializeField]). For now the only solution is to edit `.sln.DotSettings` like shown [here](https://github.com/JetBrains/resharper-unity/issues/859#issuecomment-529896414)

**Comment by vcabourdin** [comment]
> This does not actually solves the problem, as it will try to force you to use the same naming convention for **any** serialized field (public or private with [SerializeField]). For now the only solution is to edit `.sln.DotSettings` like shown [here](https://github.com/JetBrains/resharper-unity/issues/859#issuecomment-529896414)
You're absolutely right. I discovered this later but to be honest I forgot about this thread. Thanks for correcting.

**Comment by AaronZurawski** [comment]
> The inspection for "Unity serialised fields" can be disabled in _Preferences | Languages & Frameworks | Unity Engine_, but this prevents showing a warning, rather than treating these fields as non-serialised fields.

I'm just looking to disable the inspection for Serialized Fields, but I want to retain the naming and style warnings that exist for the fields. Like stated here, with disabling it, all inspection warnings are suppressed. 

Will the fix for this include that ability?

**Comment by citizenmatt** [comment]
The naming system recognises Unity's serialised fields as serialised fields. Disabling the inspections just means that inspections for serialised fields are not shown. You can update the naming styles for serialised fields to match non-serialised fields, though, and it will act the same.

**Comment by AaronZurawski** [comment]
@citizenmatt I tested it again in a fresh test project and you are correct and it seems to be working as desired. I'm not sure exactly what happened with my original test, but that also seems to be working correctly now.

If I manage to repro, I'll open a new Rider bug on YouTrack.

Sorry for the confusion!

**Comment by berniegp** [comment]
This is the inspection setting mentioned above
![image](https://user-images.githubusercontent.com/881558/118003076-85476d00-b348-11eb-95e1-41a2f2b1ff27.png)

**Comment by MeisterDerMagie** [comment]
Has this issue been addressed by now?

**Comment by citizenmatt** [comment]
@MeisterDerMagie a checkbox will be available in the next preview build of 2022.3 (EAP9, I think). This will disable Rider from recognising Unity serialised fields completely, and treat them as normal fields.

**Comment by MeisterDerMagie** [comment]
Great news, thank you!

**Comment by lucid-dreamm** [comment]
Yes, Please add a feature to turn off serialized field rule completely. It is meaningless and weird to name based on serialized/non-serialized fields.

**Comment by citizenmatt** [comment]
Do you mean older versions of Rider or Unity? Rider supports pretty much all versions of Unity (since 5.6, I think), so you can use new versions of Rider with Unity 2021.x. We don't tend to update older versions of Rider - with 3 major releases a year, updating back to Rider 2021 would mean updating 7 or 8 different versions, which isn't feasible.

**Comment by Hitomilras** [comment]
> This is the inspection setting mentioned above ![image](https://user-images.githubusercontent.com/881558/118003076-85476d00-b348-11eb-95e1-41a2f2b1ff27.png)

I disabled this checkbox and still have this warning in my code for serialized / non serialized fields... How to disable it completetly so it will work just based on visibility of the field?

**Comment by citizenmatt** [comment]
Rider 2024.2 finally includes [RIDER-8339](https://youtrack.jetbrains.com/issue/RIDER-8339), which rewrites the naming rules UI to expose custom naming rules, so you no longer have to edit a `.dotSettings` file manually. Instead, just add a new rule in the _Settings | Editor | Code Style | C#_ settings page: choose the naming style, apply it to the element kind of "Unity serialised field" and check the "Private" or "Public" accessibility checkbox. This should then allow you to have separate naming styles for private and public Unity serialised fields.

<img width="829" alt="Screenshot 2024-09-05 at 8 19 13 PM" src="https://github.com/user-attachments/assets/701d48fe-a5b3-43f1-89c8-bd9fe2053e38">
