### ISSUE TITLE
"Convert to serialized backing field" adds "readonly" modifier

### ISSUE THREAD

**Issue by IgnisIncendio** [JetBrains/resharper-unity#892]
![image](https://user-images.githubusercontent.com/1744967/48175260-4767c900-e346-11e8-81eb-48eefc5d4f0f.png)
![image](https://user-images.githubusercontent.com/1744967/48175284-56e71200-e346-11e8-8ed8-97190d8d6cc6.png)
![image](https://user-images.githubusercontent.com/1744967/48175294-5cdcf300-e346-11e8-96e9-9c16c8cd6943.png)

It does suggest to remove the readonly, but it shouldn't add it in the first place.

**Comment by krasnotsvetov** [comment]
It's ReSharper behaviour : 
When you use context action on property without setter or with setter, but setter is not used, ReSharper generates readonly backing field (same semantics). 
_test field is underlined because it is never initialized from constructor and remove readonly is not reason for highlighting. 
if you will write something like
`private float Test {get;} = 42` ReSharper will generate 
`private readonly int _test = 42`
