### ISSUE TITLE
Unability to name Unity serialized field starting with underscore

### ISSUE THREAD

**Issue by pauldyatlov** [JetBrains/resharper-unity#928]
![default](https://user-images.githubusercontent.com/17763179/49004326-1c1e1000-f175-11e8-975f-0d73b90a7c3e.png)

Why tho?

![default](https://user-images.githubusercontent.com/17763179/49004351-28a26880-f175-11e8-945e-0db4a32384cb.png)
Settings are not helping also

**Comment by citizenmatt** [comment]
The next build of Rider 2018.3 will contain extra settings here - prefix, suffix, style and a checkbox to disable inspections.

**Comment by smkplus** [comment]
Rider is bullshit!
I have similar problem
It frustrated me

**Comment by citizenmatt** [comment]
Sorry to hear that, but I'd ask you to please be civil.

This problem was fixed in Rider 2018.3, and it's possible to configure the naming convention for serialised fields to begin with a prefix set to underscore.

If you're still seeing an issue, please provide more details, including version and some repro code.

**Comment by rhinboost** [comment]
> 
> 
> Sorry to hear that, but I'd ask you to please be civil.
> 
> This problem was fixed in Rider 2018.3, and it's possible to configure the naming convention for serialised fields to begin with a prefix set to underscore.
> 
> If you're still seeing an issue, please provide more details, including version and some repro code.

Where can I find this setting?

**Comment by SugoiDev** [comment]
It's in the Settings -> Languages and Frameworks -> Unity Engine pane

![image](https://user-images.githubusercontent.com/7355630/63639599-a5fafb00-c66b-11e9-9f15-7bc6280fdb83.png)

**Comment by smkplus** [comment]
> Sorry to hear that, but I'd ask you to please be civil.
> 
> This problem was fixed in Rider 2018.3, and it's possible to configure the naming convention for serialised fields to begin with a prefix set to underscore.
> 
> If you're still seeing an issue, please provide more details, including version and some repro code.

I'm sorry 
Rider is very good
I love it

**Comment by RunninglVlan** [comment]
Sorry to post in an old closed issue, but I'm having issues with fields that start with on, e.g., `ButtonClickedEvent onPointerDown`:
![image](https://user-images.githubusercontent.com/11376741/97994631-28458a00-1dee-11eb-8210-1272ced27a19.png)
And I don't understand why I see these warnings.

**Comment by pauldyatlov** [comment]
@RunninglVlan  You can press Alt+Enter and then go there

![image](https://user-images.githubusercontent.com/17763179/97995429-c897b080-1de6-11eb-835a-6687f72d425d.png)

And add a prefix for the serialized fields 
![image](https://user-images.githubusercontent.com/17763179/97995474-d64d3600-1de6-11eb-9d75-20e1a8dc7b49.png)

**Comment by RunninglVlan** [comment]
The thing is I don't want to have some prefixes/suffixes, I tried that, they just require all serialized fields to have them.
As you see I want, e.g., 2 fields:
```
[SerializeField] bool keepOnScreen;
[SerializeField] ButtonClickedEvent onPointerUp;
```
I'm prefixing 2nd field with `on` because it's an `Event`.

**Comment by citizenmatt** [comment]
I expect you have the `on` prefix already assigned to events in the standard C# naming styles. Once a prefix is defined for a particular entity type, you will see a warning if you try to use it for another entity type. E.g. if you wanted to use `m` as a prefix for fields, to show that they are "members", then you would see a warning if you had a local variable called `mName`. To do otherwise would be confusing and defeat the purpose of having prefixes.

But that doesn't help in this situation where we have a field that is semantically an "event", even though it's not a C# event, but is a field, and more importantly, is a Unity serialised field.

I don't have a good solution right now. It might be possible to add another entity that can have its own rules (serialised field based on `UnityEvent`), but I'm not sure on ordering (how to make sure that the "serialised field" rule doesn't match these new events), and more importantly, I don't think I'd enable the rule by default, and we don't have the UI to create this rule - that is an outstanding feature request: [RIDER-8339](https://youtrack.jetbrains.com/issue/RIDER-8339). It looks like this is finally scheduled for Rider 2021.1, so once that's implemented, I'll revisit this.

**Comment by RunninglVlan** [comment]
@citizenmatt, we have some rules related to events that were autogenerated when we first created .editorconfig:
```
dotnet_naming_rule.event_rule.severity=warning
dotnet_naming_rule.event_rule.style=on_upper_camel_case_style
dotnet_naming_rule.event_rule.symbols=event_symbols
dotnet_naming_symbols.event_symbols.applicable_accessibilities=*
dotnet_naming_symbols.event_symbols.applicable_kinds=event
dotnet_style_qualification_for_event=false:suggestion
resharper_csharp_naming_rule.event=on + AaBb, AaBb
```
But I can't say that I saw them in action anywhere.
For example, we have the following event: `public event Action EntitiesCreated = delegate { };`
No warnings here.
I tried subscribing to it with local variables:
```
Action onEntitiesCreated = () => { };
Action entitiesCreated = () => { };
world.EntitiesCreated += onEntitiesCreated;
world.EntitiesCreated += entitiesCreated;
```
No warnings here either, Rider only suggests using local functions instead.

**Comment by citizenmatt** [comment]
The `resharper_csharp_naming_rule.event=on + AaBb, AaBb` rule states that you can have both `on + AaBb` ("UpperCamelCase" with `on` as a prefix) style names and `AaBb` ("UpperCamelCase") style names, so Rider will accept both `onEntitiesCreated` as well as `EntitiesCreated` for standard .NET events. But because this rule is using `on` as a prefix, it means Rider won't allow `on` at the start of a name for any other entity.

<hr />

But that makes me realise that there is of course a workaround. 

Since we can have multiple naming policies for a given rule, we can add an extra policy to the serialised field rule to allow `on + AaBb`. The only problem is that Rider doesn't have a UI for adding or editing custom rules, only the specific static rules already available in the UI. This is why the UI for serialised fields is in the Unity preferences page - the Unity plugin automatically adds a custom rule for serialised fields. ([RIDER-8339](https://youtrack.jetbrains.com/issue/RIDER-8339) is the ticket for adding support for custom rules.)

Fortunately, we can modify the settings manually. Add the following line to either `.sln.DotSettings` or `.sln.DotSettings.user`, depending on if you want it checked into source control or not.

```xml
<s:String x:Key="/Default/CodeStyle/Naming/CSharpNaming/UserRules/=5f0fdb63_002Dc892_002D4d2c_002D9324_002D15c80b22a7ef/@EntryIndexedValue">&lt;Policy&gt;&lt;Descriptor Staticness="Instance" AccessRightKinds="Any" Description="Unity serialized field"&gt;&lt;ElementKinds&gt;&lt;Kind Name="UNITY_SERIALISED_FIELD" /&gt;&lt;/ElementKinds&gt;&lt;/Descriptor&gt;&lt;Policy Inspect="True" Prefix="" Suffix="" Style="aaBb"&gt;&lt;ExtraRule Prefix="on" Suffix="" Style="AaBb" /&gt;&lt;/Policy&gt;&lt;/Policy&gt;</s:String>
```

It's not a nice file format (yes, that's encoded JSON inside XML!), but this adds an `ExtraRule` with a prefix of `on` and "UpperCamelCase". So Rider will now happily match both `onPointerUp` and `pointerUp` for serialised fields.

**Comment by RunninglVlan** [comment]
Thanks, adding the rule solved the problem. Thanks for clarifying this too:
> But because this rule is using on as a prefix, it means Rider won't allow on at the start of a name for any other entity.

With this knowledge I solved other warnings - we had `Action` parameters in methods with prefix `on`.
