### ISSUE TITLE
How to build Unity Support locally for Resharper?

### ISSUE THREAD

**Issue by sorencoder** [JetBrains/resharper-unity#975]
Is it possible to build Unity Support plugin for Resharper locally?
I'm referring to the extension that we add through Resharper/Extension Manager window.

**Comment by citizenmatt** [comment]
Good news and bad news here. The good news is that it should just build from checkout - run `.\build.ps1` and everything should get restored and compiled. To get a ReSharper extension package, you can run `.\build.ps1 packReSharperPlugin`.

However (the bad news), this hasn't been tested since the 2018.2 release, and a lot has changed in this release, so I have to say that I don't expect this to work with the existing codebase. I'm working on this now, and should have a 2018.3 release for ReSharper in the next few (work) days. See #853.

I'm going to close this issue for now, if you have more questions, feel free to post here, or follow #853

**Comment by sorencoder** [comment]
I build the extension with `.\build.ps1 packReSharperPlugin` command. It went ok. How can I install it on visual studio?

**Comment by citizenmatt** [comment]
You would need to add a new package source to ReSharper's Extension Manager options page, and point it to a folder, e.g. `c:\packages` and make sure the `JetBrains.Unity.XXX.nupkg` file is copied there. Ideally, it will now appear in the Extension Manager.

However, because this hasn't been updated since 2018.2, it might not be visible in Extension Manager. You might need to edit the `.nuspec` file to change the dependency on `Wave` to be `[183.0]`. It should show up then.

BUT. I'm very confident that you'll still have problems, mostly because there is a new .dll that won't be installed (`JetBrains.ReSharper.Plugins.Yaml.dll`), although there could easily be other issues, too. Furthermore, because ReSharper uses a component container to construct class instances, and create class dependencies, and because this is the main extension point, exceptions during class construction (such as not having a .dll available) might have a cascading effect and break a lot of ReSharper functionality.

**Comment by sorencoder** [comment]
> BUT. I'm very confident that you'll still have problems, mostly because there is a new .dll that won't be installed (JetBrains.ReSharper.Plugins.Yaml.dll), although there could easily be other issues, too. Furthermore, because ReSharper uses a component container to construct class instances, and create class dependencies, and because this is the main extension point, exceptions during class construction (such as not having a .dll available) might have a cascading effect and break a lot of ReSharper functionality.

OK. I will wait then. 😶😶
