### ISSUE TITLE
Feature: Action to Launch Unity Docs for selection

### ISSUE THREAD

**Issue by Ethan-VisualVocal** [JetBrains/resharper-unity#98]
This is a lame request, but MonoDevelop and VSCode+UnityPlugin both have a handy shortcut (CMD+' on MacOS) to launch external documentation for your selection. 

I replicated the desired functionality in Rider using the following:

1. Add new "External Tool" that runs `open` in the console and passes it: https://docs.unity3d.com/ScriptReference/30_search.html?q=$SelectedText$ 
2. Record new macro that runs the action `EditorSelectWord` (expands selection from cursor to entire word) and then the action to run my new "External Tool" 

This works fine for me, but new Rider / ReSharper + MSVS users moving from MonoDevelop or VSCode will try that basic shortcut, then look to bind it, and find that the "External Documentation" shortcut doesn't do anything and that QuickDoc, while helpful, doesn't replace that function.

(I couldn't find a way to configure External Documentation in Rider, maybe this is a Rider EAP specific issue?)

**Comment by mxplusb** [comment]
@Ethan-VisualVocal  I was actually just in the same situation you're describing. I followed your steps, thanks!

If you're on Windows/Linux, when you set up the "External Tool" `Program` field, you have to call your browser directly, i.e. `%DIR%\path\to\chrome.exe`. For Step 2 of Ethan's functionality, on Windows using the `Visual Studio` keymap, the `EditorSelectWord` feature keymap is `CTRL+W`, you can find it on "Edit" > "Extend Selection". I searched for the second one for awhile, so I figured I'd leave a comment. :)

**Comment by mxplusb** [comment]
Also, if you're hardcore, you can actually map the macro you created to `CTRL+'` in "File" > "Settings" > "Keymap" > "Macros" folder at the very bottom.

**Comment by mxplusb** [comment]
Also, see: https://youtrack.jetbrains.com/issue/RIDER-4316

**Comment by CAD97** [comment]
On Windows, you can use `start` to open a HTTP URL with the default web browser.

**Comment by citizenmatt** [comment]
So Rider has an _External Documentation_ action that should do this. It's a shortcut, and is an icon that is shown on the _Quick Help_ popup (as discussed in #190).

BUT, Rider doesn't support _External Documentation_, because it doesn't have the information needed. IntelliJ requires a URL to navigate to, but ReSharper's _Read More_ link isn't a URL, but an action that causes ReSharper to either show product help, or invoke Visual Studio's MSDN keyword navigation/search. This plugin intercepts ReSharper's request to VS for Unity types, and navigates somewhere useful, but this is too decoupled for the bridge between IntelliJ and ReSharper's quick help systems. I suspect an API change in ReSharper is required, but there may be a workaround in the meantime.

**Comment by citizenmatt** [comment]
There isn't a satisfactory workaround. I can only get a URL by hiding it in the QuickDoc content, and I can only make that work for Unity event functions and parameters. This means it doesn't work for normal Unity types and type members, and only works when displaying the QuickDoc popup, not when using the _External Documentation_ command, which doesn't open the popup (and so doesn't fetch the content, so doesn't get the URL).

And we can't do it all front end, because we don't know what's under the caret (i.e. can't get fully qualified type, can't resolve event function, can't get event function from current parameter). This requires back end information, but needs a new API. Perhaps this is a good candidate for extending the protocol?

**Comment by insominx** [comment]
Based on the above, I was able to make this work on windows using the following:
![image](https://user-images.githubusercontent.com/180210/81456428-19d02b80-9147-11ea-928b-cd79b479d8f9.png)

**Comment by citizenmatt** [comment]
Can I ask what the scenario is here? For a Unity symbol, you should be able to invoke the Quick Documentation action, and click the "external documentation" link to open local documentation if installed, or search the Unity site if not. Does this help for your scenario?

<img width="683" alt="Screenshot 2020-05-09 at 5 30 04 pm" src="https://user-images.githubusercontent.com/222659/81479404-dc3cd280-921a-11ea-83b2-1196dc2ef1d7.png">
